package com.ss.aoc;

import java.util.Arrays;

public class Day02 {
    private String inputData = "3-4 l: vdcv\n" +
            "6-9 d: dddddkzdl\n" +
            "6-13 f: mfswqfrqffrvfvf\n" +
            "10-12 l: sfzlnwcptlnlflq\n" +
            "2-4 m: qbwcmt\n" +
            "15-16 v: vvvvvvvvnvvvvcvvvvgv\n" +
            "1-4 n: wnnzfln\n" +
            "1-3 x: xxgx\n" +
            "7-8 j: jjjjjfvh\n" +
            "6-8 x: xxzxxnnwx\n" +
            "3-8 t: djtdznbtgwtrhxf\n" +
            "7-9 w: glwwwwxtxwlwwwcp\n" +
            "4-5 g: jggjtgggg\n" +
            "9-10 c: trgjrcbfcwf\n" +
            "9-10 v: vvvbvmvcvvvv\n" +
            "3-14 p: pptzpppppppppsfrsppc\n" +
            "3-5 n: nnznmkn\n" +
            "1-13 t: fxtrpgtzztsfnmzmmtg\n" +
            "13-15 d: dcztmqjdmclgdhdcd\n" +
            "3-4 j: mjjjjc\n" +
            "13-18 x: fxxgxxxxxxxxxxxxxcx\n" +
            "2-4 f: fxqs\n" +
            "3-4 w: ffmbwwnn\n" +
            "12-13 k: dlpdzkhbkkkftkb\n" +
            "5-11 r: vrdxrrrrrtrqz\n" +
            "7-8 b: bbbbbbrcb\n" +
            "13-16 c: wzccvzccclccczcc\n" +
            "10-11 m: lmmmmmmmmwqmm\n" +
            "6-10 f: fffqjfznvfhz\n" +
            "8-9 h: hvfhhvgklhhpfmh\n" +
            "4-17 p: hpprnpsppcppppppfp\n" +
            "9-13 z: zzzzrgtzzzzzzzzzzl\n" +
            "6-10 l: lllllqlllplll\n" +
            "3-10 j: vjjjwjjjjjjjj\n" +
            "4-8 j: jjjjjjjjjjc\n" +
            "2-5 s: jsgtsfsw\n" +
            "1-2 b: brwpbbbbb\n" +
            "2-5 m: tbkpfbvnqmpjbbx\n" +
            "7-8 m: xxbgmbmnmmwmdhmm\n" +
            "9-12 v: phsslrznvrsvtxgv\n" +
            "10-14 v: rnnvvrvvvzbhmcx\n" +
            "13-15 b: bbbbbbbbbbgbwbbb\n" +
            "2-5 w: bwldjwwz\n" +
            "5-7 d: dddjthk\n" +
            "10-12 c: pckcccccccccl\n" +
            "2-11 b: rdjqkdbzxzqfgn\n" +
            "3-8 s: dsssmshs\n" +
            "8-10 d: dddfdddsdj\n" +
            "2-4 l: slgltjzwzrnlllrh\n" +
            "6-10 z: vrcvgrgzphxd\n" +
            "10-13 b: mnblbbbbbbbfvbbbbx\n" +
            "8-16 n: wznnnbfhndnnnnngnn\n" +
            "6-8 v: fvvvzqks\n" +
            "3-6 n: znqnbnzwnn\n" +
            "15-16 g: wggzxsgcgjwgxhgggg\n" +
            "10-13 x: xlvxxxxxkxxxfxx\n" +
            "2-6 z: jpznbgszmj\n" +
            "13-19 j: jjzjjjdjwxlnjhwsrtj\n" +
            "5-6 p: bvppqqppcp\n" +
            "19-20 r: rrrrrrrrbrrrrrrrrrvd\n" +
            "4-7 j: jjjjjjljj\n" +
            "5-6 k: kkkkkck\n" +
            "1-2 k: zbkk\n" +
            "11-13 r: rrsrrrwrrrrrr\n" +
            "6-11 z: zzgzznzzzzwzzrzpzgc\n" +
            "7-11 l: llvlllllllllllll\n" +
            "7-8 f: fffffjffnp\n" +
            "3-4 j: pxcw\n" +
            "9-11 k: zkkkkkkkdkzx\n" +
            "12-13 g: fgglgvggxhgks\n" +
            "6-7 d: kbdddftdddl\n" +
            "14-15 m: dmmjwnxxfdfhwvcdd\n" +
            "3-4 b: bbbsbt\n" +
            "2-9 d: tgsvznmnnrgvtldjbj\n" +
            "4-5 l: ljxtc\n" +
            "5-8 j: jnvsjlfw\n" +
            "3-4 v: zrklbf\n" +
            "1-15 v: vvvvvvvvvvvvvvtv\n" +
            "5-6 n: ssnnnngnsxkphtnwrk\n" +
            "6-7 k: kkkkkkdk\n" +
            "2-4 d: xchmdk\n" +
            "12-13 v: vfvvmvvvpvvwvpvvvdm\n" +
            "3-14 d: dzcddwdddddfdfdwd\n" +
            "1-6 b: dbbbbsb\n" +
            "12-14 b: bbbxbbbbbbbjbb\n" +
            "1-8 s: sssssssgn\n" +
            "5-10 d: ddddwddddvdd\n" +
            "10-12 s: sssmssssskswssss\n" +
            "3-13 q: cdqfcqvszbzqnhvxlw\n" +
            "8-10 z: tmgzkvxzzvz\n" +
            "8-10 n: nnnnntnqnhrsnn\n" +
            "2-7 r: vjrctrhprhc\n" +
            "6-8 w: bzfxrwwfmx\n" +
            "3-5 x: xxxwxb\n" +
            "5-9 z: vbspkzfsrrpdcfl\n" +
            "8-9 z: jgqzzzzzwq\n" +
            "5-12 x: dvqvjsdfjxgtxkd\n" +
            "5-6 r: rrrrrr\n" +
            "1-4 f: xdzngd\n" +
            "15-18 x: xxxxxxxxxxxxxxvvxx\n" +
            "1-4 g: qcwjpxgtvgkf\n" +
            "13-15 m: mhmmmmmmmhmmqmmmmmmv\n" +
            "5-11 n: nnnndnnnnnnnnnnnn\n" +
            "4-9 n: tjgnpqsnpxpzfw\n" +
            "10-13 q: qqlqdqqqqqqqnqq\n" +
            "8-14 g: gdcggnknjsgdskq\n" +
            "3-5 l: vlllll\n" +
            "16-18 t: ttttttttttttttttmt\n" +
            "9-14 b: kbhbcbbbbbqbsbr\n" +
            "3-9 f: jzrnxffljfmhffftdng\n" +
            "1-4 z: pbzs\n" +
            "10-11 h: lrrgpmhshtfg\n" +
            "1-5 n: mnqjwjpfnnzn\n" +
            "1-8 r: zrrrprrkr\n" +
            "8-9 g: gkbtggcpf\n" +
            "3-8 q: qqsqqgqqqqm\n" +
            "17-18 j: jjjjjjjjjjjjjjjjgkj\n" +
            "13-14 t: tttttttttmtttfttt\n" +
            "2-6 c: cvcccqc\n" +
            "4-17 c: sfnckrcmlcpmcpcgbkct\n" +
            "10-12 d: dddddddqvddd\n" +
            "3-5 d: ddddtd\n" +
            "10-11 h: hchhhhhhhvg\n" +
            "3-11 j: mmlcjsjhjbpjjjxsk\n" +
            "11-12 w: wwwwwwwwwwwww\n" +
            "9-10 c: ccccccccccc\n" +
            "5-7 x: ckhdnfgjrdkxqphvjtvs\n" +
            "10-12 s: ssssjsssshstd\n" +
            "7-8 m: mmmmmmmg\n" +
            "3-4 v: vjvvt\n" +
            "2-3 f: hmknf\n" +
            "3-5 g: bgsglggg\n" +
            "12-13 x: vxxxdcgxxxfxx\n" +
            "3-20 h: hhhtkvrmfswvmkzmbvmh\n" +
            "2-3 v: vvvv\n" +
            "3-14 g: zgpggzgqxjzggg\n" +
            "15-16 c: ggcjccnccccccccc\n" +
            "11-12 d: wrdrdxsfdzddkl\n" +
            "6-7 q: vqqknqq\n" +
            "2-6 w: wwwwwwwkck\n" +
            "4-6 l: dplldljlvxrrm\n" +
            "2-18 m: pmwfkqlknsxzjmdzkmxd\n" +
            "5-11 q: rqkzqxqmqtqnzqqqxk\n" +
            "6-7 s: sssssskss\n" +
            "9-10 w: wwwwwwwwsw\n" +
            "5-7 x: jxxxhxwxxxxxxxx\n" +
            "4-5 t: ttbttfm\n" +
            "2-4 h: mlhhhkhc\n" +
            "13-14 l: llllllllllllfjl\n" +
            "8-10 k: kllkkkjkkkk\n" +
            "1-3 s: sssbdss\n" +
            "2-3 z: zlbzzzzzz\n" +
            "9-10 r: rrvrrrfrdfrr\n" +
            "4-12 k: vkkkbkhkzkkk\n" +
            "11-12 l: llllllllllcgc\n" +
            "5-6 k: hkzkkkkgdsghdk\n" +
            "3-5 n: nzsxk\n" +
            "12-14 r: rwrrrrrrrrrprxrrr\n" +
            "4-7 k: kkxkkkkkkk\n" +
            "12-16 b: bbbbbbbbbbbbbbbbb\n" +
            "13-16 p: ppppppppppppzppfp\n" +
            "15-19 j: tjjjjjdjjjjmjjccbjm\n" +
            "1-3 l: llll\n" +
            "3-4 x: hxkl\n" +
            "9-15 n: ktnpmnnnlnxnnft\n" +
            "6-7 q: qqdtcqs\n" +
            "13-14 g: lgghndddgllnfg\n" +
            "7-14 k: cdzkjkkksksbwkjb\n" +
            "7-11 w: cwcsvqwfwhw\n" +
            "14-18 m: mmmmmmmmmmmmmhmmmjmm\n" +
            "4-5 c: cvfctcsncscbmj\n" +
            "4-5 r: zrnrrnxct\n" +
            "2-3 b: ggdlb\n" +
            "8-9 x: cpxskxxxxbxn\n" +
            "12-14 v: vvvvvwvvvvvbvw\n" +
            "13-16 n: pmhnhpnntncxqrmd\n" +
            "2-4 m: mmxm\n" +
            "7-10 m: mmmrqwsmnkgbdbrmmjjm\n" +
            "7-8 z: zzzzzzzzzz\n" +
            "2-3 p: pppnfltzpd\n" +
            "1-10 h: hhslhfsgtxphhncg\n" +
            "5-6 m: txmhxhtmgm\n" +
            "4-5 v: wsnvrsvx\n" +
            "8-12 p: pfbdlnrphdfplvpqx\n" +
            "10-13 b: nbpjvgghsbplb\n" +
            "9-15 h: ghcxbptxsgvvvptqx\n" +
            "4-5 t: tttgf\n" +
            "2-3 l: lsnl\n" +
            "1-11 v: vvvvvvvvvvvvvvvv\n" +
            "6-7 r: brnrrrr\n" +
            "3-4 k: bkkvkrtmzj\n" +
            "17-18 p: pppppwphpkpppppppp\n" +
            "8-11 f: fqfffdffffpfffffffff\n" +
            "14-16 z: zznzzzbzzzzdzzzsz\n" +
            "10-11 v: xtvfnxdrvqnxg\n" +
            "8-13 c: tcwtbcpfvdccs\n" +
            "5-6 b: btbnbdb\n" +
            "2-4 d: ddxmcb\n" +
            "6-9 p: qpppzppbpsplpppppxp\n" +
            "7-12 z: zzzzzztzqzzqzz\n" +
            "4-5 h: hhhmb\n" +
            "7-10 f: frftffhfff\n" +
            "4-5 c: xccmv\n" +
            "8-11 x: rfglxxxhxwvxxfcxx\n" +
            "7-10 k: kkqnjxzckmmbkkk\n" +
            "6-7 h: hhxsdhhwh\n" +
            "15-18 r: rmrrlrrrrrrrrtncrcr\n" +
            "10-11 x: srnxxbbhxxx\n" +
            "13-14 c: cccccccccccchx\n" +
            "5-8 r: rrrrfrrhrrr\n" +
            "11-15 v: vvvvvvvvvvvvwvvvsvv\n" +
            "6-8 q: qqkqlnqzmqqx\n" +
            "2-3 h: hhzq\n" +
            "10-12 l: lllflllllpqt\n" +
            "7-9 m: mlmmmmmmm\n" +
            "4-12 b: pbbhbrrhzxvrgcsfmqq\n" +
            "8-10 g: tggrgggbgdggmg\n" +
            "9-10 s: sssssksspsss\n" +
            "4-8 k: dtkkkkkkkkkkmk\n" +
            "19-20 j: jjjjjjjjjjjjjjjjjjjj\n" +
            "3-8 r: rrrrxrrrrrrr\n" +
            "9-10 p: qmgzfbqpnp\n" +
            "1-4 w: wwwsw\n" +
            "1-15 f: fffffffftzftxhfwfbx\n" +
            "1-5 t: rtttttlxtjtttsq\n" +
            "3-4 f: fmffkt\n" +
            "16-18 n: kfnnnlnnnsgscnzmrv\n" +
            "3-4 w: wwmk\n" +
            "7-9 l: lllkbllllllllljtjll\n" +
            "7-13 l: pqzbtxmqslllqkx\n" +
            "6-18 j: qlnjjvrtzqkfrnjxjk\n" +
            "6-8 q: qtpqqpqg\n" +
            "6-8 c: cccfccxd\n" +
            "3-4 f: fhff\n" +
            "4-5 x: xjxfhqkhx\n" +
            "16-18 k: xvbktrmqkckwkrkkjkk\n" +
            "9-13 v: vvvbvvvvvvvvnvvlmvv\n" +
            "1-7 k: wkkkkkqkk\n" +
            "2-4 z: jpzlxfjbh\n" +
            "5-8 l: lllllpllfllllr\n" +
            "7-8 r: rrrrrrwnr\n" +
            "5-6 d: ddddftd\n" +
            "4-5 q: vqlqn\n" +
            "3-13 p: pppsppmpbppppppppn\n" +
            "1-3 w: wwww\n" +
            "4-5 d: tfrpfcdlft\n" +
            "5-10 r: rrrrppxrrvrm\n" +
            "9-10 t: dtttttttgvtt\n" +
            "8-12 j: jjjhjjjljjjjjpjj\n" +
            "6-7 b: lpfpzljhbl\n" +
            "3-6 k: kzkqkrkckkv\n" +
            "3-7 q: rvqdtsqqjfftzllflnx\n" +
            "2-3 l: glsjcsrlmn\n" +
            "5-8 g: gggxhggpgg\n" +
            "12-14 q: zqqsqqqqqqqqxqqq\n" +
            "9-11 q: qqqqsqjtqqq\n" +
            "9-10 g: gggggcggggg\n" +
            "12-14 z: zzzzzzzzzzzlzzzzzz\n" +
            "1-6 s: gvqttcgrqqsbndv\n" +
            "8-19 z: mzzzpkzdzzzskfhzzlj\n" +
            "4-6 h: kmlbhwthhp\n" +
            "8-9 x: xxxxxxxvk\n" +
            "1-2 k: drjkkkk\n" +
            "10-12 z: zdzsgzzzwvzrzszzzzzz\n" +
            "13-14 f: lffdffjfbfdxjd\n" +
            "11-12 b: rppkbnjgcqrr\n" +
            "1-2 l: lllq\n" +
            "5-6 m: mmmmzr\n" +
            "6-14 l: lllbldllpllllblllcl\n" +
            "4-9 d: rdtdcwnbqjbthddr\n" +
            "13-15 v: vvcwvvqvzvvvfvg\n" +
            "9-10 g: gpxpwxhmgg\n" +
            "13-14 n: njpndvsvfgrrhnb\n" +
            "3-5 r: rrrrr\n" +
            "7-13 h: hhdcgscdxmhwhg\n" +
            "3-4 l: tnhf\n" +
            "10-13 c: mfcvbcmcccqhc\n" +
            "6-7 x: cdwfdxxxxxx\n" +
            "5-7 b: wbbzwbcx\n" +
            "4-6 h: vhhzpqjhk\n" +
            "5-8 r: hffprngr\n" +
            "14-15 p: pppppppppppspjm\n" +
            "8-12 z: pzqdhzzkzzzzxzzc\n" +
            "1-8 b: kbbfdvvcsdjlbw\n" +
            "16-18 k: rqwtgtwzgsnvlkdkkk\n" +
            "8-10 w: xllfslwwsf\n" +
            "2-5 m: qmbdm\n" +
            "10-12 b: bhbbbbbwtbbbbbhbb\n" +
            "8-14 c: cscdccccccccxcp\n" +
            "3-5 c: rcdpz\n" +
            "16-18 q: qqqqqqqqqqnqqqqbql\n" +
            "3-4 x: xjxx\n" +
            "6-7 n: gnnnnxwqn\n" +
            "16-17 f: tffrffffffffffffff\n" +
            "5-6 d: ddddgm\n" +
            "2-7 r: prrrssrrkrjrrr\n" +
            "12-16 g: ggxbxggtgbggccwgggtv\n" +
            "10-14 n: nnkntpnvncnnnznnr\n" +
            "3-5 c: qccwcx\n" +
            "7-17 v: jvvvvhvvvpvvqvgvv\n" +
            "3-6 c: cclccs\n" +
            "8-10 m: nwtmfcnmmmmm\n" +
            "1-2 p: hrpp\n" +
            "2-3 j: hdnjgt\n" +
            "1-3 h: jhgvhjhh\n" +
            "9-10 j: jjjjjjjjvl\n" +
            "12-15 h: hhshhhhthhhhhnhn\n" +
            "5-8 k: qkvmkwckvlkl\n" +
            "12-15 j: jjjjjjjkjjjwjjlj\n" +
            "11-16 v: tvmrmvvvwwqrxwvg\n" +
            "5-7 b: dbhtpjvxqzbhbz\n" +
            "3-4 b: mqbg\n" +
            "4-7 t: tttbtvt\n" +
            "8-13 h: hhhhchhhhqfhhhhhthr\n" +
            "1-6 w: lhwqgrbbwbv\n" +
            "1-11 t: ttttpttttttt\n" +
            "2-5 l: rlwllvfhw\n" +
            "7-8 m: jmmrmmmmlmmm\n" +
            "3-5 s: smsss\n" +
            "15-19 p: mfpzcghppcgpgqpfvxfw\n" +
            "6-7 n: jnldsnb\n" +
            "7-9 x: xwbwdxjhcxxvxx\n" +
            "1-2 c: cbqprgfjfpc\n" +
            "3-4 g: gngf\n" +
            "7-10 w: twvvwwtwwtwwsgwws\n" +
            "2-9 g: ggngggglgrzk\n" +
            "7-9 p: xpphpkppppp\n" +
            "11-12 p: pppppxpppppppppp\n" +
            "3-4 g: fzqrl\n" +
            "6-7 x: xxxxxmw\n" +
            "3-4 r: rrrn\n" +
            "8-11 b: bbhbbbbrbbwbkb\n" +
            "3-11 d: xxvfmvrdmzhfmvmhhp\n" +
            "1-12 z: mzzzkzwzzzxfzzzzzzzz\n" +
            "5-11 g: gzbjgxghddggkgq\n" +
            "5-8 g: grpggrgg\n" +
            "1-6 f: lfffffsfffff\n" +
            "8-10 x: slxxxgxxqxxx\n" +
            "4-13 l: lllllllllllllvll\n" +
            "8-9 z: zzzzdhzzz\n" +
            "13-15 l: rglrmcqvgjzvlklx\n" +
            "2-4 q: nsxs\n" +
            "2-3 v: vvqcv\n" +
            "13-14 b: bbbbbbbbbbbbbb\n" +
            "13-14 x: rxxdxnxxtxxxqq\n" +
            "1-4 s: jmsssssgssvppss\n" +
            "6-7 j: pgvjkxcvjslmj\n" +
            "2-5 w: jwwswgl\n" +
            "5-7 m: mmnmmxp\n" +
            "2-6 k: tkkkxwtkrk\n" +
            "4-15 n: nnnnngnnnnnnnnnnnt\n" +
            "7-11 x: dxxtxxxvwtnx\n" +
            "11-14 s: ssrvphskdsstzsszrnsz\n" +
            "11-12 l: rclllgbllblb\n" +
            "6-7 x: fxhbmnj\n" +
            "15-17 q: kqvhwsqhqqqhmqqtqqlq\n" +
            "12-14 k: kksktkkkkkkkkfk\n" +
            "3-4 h: hshk\n" +
            "14-17 v: vvvqvvkvvvvvvvjkvxv\n" +
            "2-6 f: vfvfrp\n" +
            "4-12 z: bzzqszhwffrhr\n" +
            "2-9 b: sbdjfbndbhcclrmblccn\n" +
            "11-13 j: jjjjjjjjjjgjkjjjjj\n" +
            "15-17 f: fpffffsfffffffdfjfff\n" +
            "6-7 v: tlvvvvv\n" +
            "11-19 l: llllllllllllllllllll\n" +
            "1-6 w: wwbwwwwww\n" +
            "3-7 s: cpsvmss\n" +
            "2-11 r: rrpnkchfzljwxmrrvvw\n" +
            "7-12 n: msgpplgpfnkmxlm\n" +
            "4-13 f: sjpfqpnzqzznfftfhgfs\n" +
            "13-14 q: qqqqqqqqqqqqqqq\n" +
            "13-14 j: jjjmjjjjjjjjgq\n" +
            "2-4 q: qdrds\n" +
            "5-10 s: ssssqssssbs\n" +
            "6-8 c: ccdcchchcc\n" +
            "18-20 z: xztgqzzckzgcpzzzjzdz\n" +
            "5-8 z: ctpdzzzzzqzmvzxn\n" +
            "6-8 b: bbmkgbfkb\n" +
            "2-10 x: xxxxxxxxxxx\n" +
            "5-6 z: gzzzqk\n" +
            "4-7 c: cccvccj\n" +
            "7-8 d: dddddddd\n" +
            "9-11 c: ccdccfccxcccc\n" +
            "1-4 z: zjzzzz\n" +
            "6-8 z: zlmjbzvz\n" +
            "8-10 v: gvtjvgvzvjphscn\n" +
            "8-10 d: dcdddddddddddddd\n" +
            "7-8 p: mjpwppppp\n" +
            "1-11 w: wwwwwnwwwwwww\n" +
            "7-9 j: jjjjjjjjj\n" +
            "6-8 q: dmqdqqzt\n" +
            "3-10 p: tsqcpgmzgh\n" +
            "11-15 s: ssslsxrlbfqsssssss\n" +
            "5-10 m: dpmtmhbdmk\n" +
            "3-5 p: wpjqv\n" +
            "10-13 p: lhvkzxprppmtprj\n" +
            "4-6 w: nlfjwz\n" +
            "19-20 c: kzckcfsqpdvssgcgktcm\n" +
            "1-2 p: ppgltbv\n" +
            "3-4 w: ngwwfttwqg\n" +
            "10-11 p: ppppppnpllgp\n" +
            "2-4 t: tkttptt\n" +
            "3-6 x: xwrjpcf\n" +
            "14-17 q: qcqbqfqqkqdqrqqqq\n" +
            "4-8 n: qsncdnbknpn\n" +
            "8-10 s: wzscpmssrshh\n" +
            "3-8 p: pfppppgpp\n" +
            "11-15 b: tqdbgfbbbgjbbbg\n" +
            "12-15 h: lwhhjzhpmhzhhnhmhh\n" +
            "4-5 w: nwccwlpwdvtlwwr\n" +
            "11-16 w: wwwwwwwwwwswwwwxw\n" +
            "6-9 q: qqqqqqqqqqqqqqqq\n" +
            "8-12 t: tqttjtttpgbtlt\n" +
            "14-15 v: vvvvkvgvvvvvvvg\n" +
            "2-12 f: fpfflxzxffwxfvfff\n" +
            "7-12 m: hmmmmwmmbmlm\n" +
            "2-3 z: mmlzzz\n" +
            "12-16 h: hhbhhhkhhfhpbghm\n" +
            "15-18 s: ssssxsssssmsssqssx\n" +
            "8-9 s: sqsqdtmssqscxxs\n" +
            "1-10 n: nnbnnngnnn\n" +
            "10-14 c: ccbcvscncrccng\n" +
            "7-8 k: kkhkxrkkctkpjkkck\n" +
            "10-11 g: bgpgggkcwzs\n" +
            "9-17 l: llllllllckwllllllwl\n" +
            "7-12 q: gqqqjbxtqvqxzjhvjrjj\n" +
            "1-3 s: ssnsc\n" +
            "3-10 n: nnnnnnnnnnnnnnnn\n" +
            "9-12 l: blfnqllsllll\n" +
            "5-8 s: sgsgstssl\n" +
            "1-4 c: cccwcc\n" +
            "7-9 h: hhhhhhhhhhh\n" +
            "2-4 s: sssss\n" +
            "8-10 f: vznpfffrsffscgfzft\n" +
            "4-5 r: hnrns\n" +
            "4-5 z: zzzlgz\n" +
            "10-18 w: wwwwwwwwwwwwwwwwwwww\n" +
            "3-12 b: bfmbbbbfbbltbg\n" +
            "14-15 z: zzjxrhrjsbrrzgd\n" +
            "1-2 z: zzzzz\n" +
            "4-11 x: pxgxwphxmgxpt\n" +
            "1-16 c: cbgnxcccxsrcbmcvqc\n" +
            "3-6 n: cnppnnjnxnnjss\n" +
            "8-9 r: zltfbjwrrlmtrzqrh\n" +
            "1-3 z: zzqzzzzzzz\n" +
            "4-7 n: vgndgdndbxcnznxc\n" +
            "2-9 w: wwwwwcfnww\n" +
            "1-4 b: tbbrbbbbbcbbbbbbbbdk\n" +
            "7-8 h: hhhwhzhhhhtf\n" +
            "12-13 j: jjjjjjjjjjjjj\n" +
            "2-8 m: rthcgnxmm\n" +
            "2-7 l: glzctbjh\n" +
            "5-7 d: dddddddx\n" +
            "12-13 x: xxxxxxxxxxxxs\n" +
            "6-11 t: ltnfnnqttvtkjnlk\n" +
            "6-7 x: qxxxxpfxxx\n" +
            "1-3 d: kdndzd\n" +
            "6-11 f: zfxfmffptsffmffvfz\n" +
            "1-4 x: xxxxxxx\n" +
            "4-5 l: lllllllll\n" +
            "4-8 c: cjccccgckrdpvv\n" +
            "13-14 z: zzzwzzzzzzzzkkzp\n" +
            "1-3 r: lgtr\n" +
            "3-17 g: ggtgjgmggggggggggggg\n" +
            "4-5 q: qqqqqq\n" +
            "2-6 v: vvvlvvv\n" +
            "4-17 c: nwqcprgftnqgcrjpcjb\n" +
            "7-10 x: xlxfrjxxxxgnxx\n" +
            "2-14 q: qqqqqqqqqqqqqsqqq\n" +
            "4-8 x: xxxxxxxxxxx\n" +
            "1-16 z: bzzzzzzzzmzzzzldzzzz\n" +
            "2-4 v: bffhzd\n" +
            "3-4 r: rrrr\n" +
            "5-8 x: xxxxxnsxd\n" +
            "1-17 g: gbngjggxgggjgzvjk\n" +
            "2-3 b: sgbb\n" +
            "11-14 p: ppppppppppppppp\n" +
            "3-9 q: vhsjtqppqgdqdqlf\n" +
            "1-3 w: wcwzsfzwwcwdwncwp\n" +
            "7-11 f: ffffffdfffff\n" +
            "3-8 g: ksgdcqqgtkmgjbzsf\n" +
            "5-8 s: tsssccswss\n" +
            "1-7 r: brrrrrhrrrrr\n" +
            "5-7 g: ggxmgggcwgz\n" +
            "2-4 h: hhwh\n" +
            "9-18 w: wwwwwwwwhwwwwwwwwbw\n" +
            "1-7 m: ndmmbmmmmmmm\n" +
            "5-7 j: jjvjvjt\n" +
            "3-8 m: plnmcmkfmmcm\n" +
            "4-5 r: rrrjzr\n" +
            "4-8 k: kkkgkjknkjkk\n" +
            "17-18 s: srngdqpwxcrbqrprss\n" +
            "4-9 t: mbkjrtntztrttt\n" +
            "1-10 w: hwwwwwwwwwwtx\n" +
            "5-9 f: lfvhfxndfffmxhf\n" +
            "7-8 n: pnnnnnbvnnnnnnnnnhnn\n" +
            "1-10 b: jjtptpmmqv\n" +
            "1-3 p: rqppqt\n" +
            "1-11 t: pbtwdttkttmtxj\n" +
            "5-6 g: jpkfggtcmj\n" +
            "6-8 f: fffffpfvf\n" +
            "9-13 t: ttttttttdtttg\n" +
            "3-5 r: prrjr\n" +
            "18-19 b: bbbbbbbbbbbbbbbbbbb\n" +
            "5-7 v: vjvjxjhvrv\n" +
            "8-10 z: zzzsznzxttgspzzzz\n" +
            "5-13 m: mngmcbmqbxmzjfm\n" +
            "1-3 b: xbhb\n" +
            "12-14 m: mfmmbgmmmmmcmz\n" +
            "3-6 n: jpnpnnn\n" +
            "3-14 j: xmgjqkzfctctxwgjms\n" +
            "7-14 k: lbkfcbctkgkjkqvjdwkc\n" +
            "6-8 l: lhthfgllfvbpxchct\n" +
            "5-6 h: hhhhhk\n" +
            "6-9 c: qkxtbqltkzcrdcgckncc\n" +
            "13-15 w: fhsvgcxwfcgxwvwwwkb\n" +
            "3-4 c: cccmcj\n" +
            "3-4 m: mhmcmm\n" +
            "4-5 k: skkqg\n" +
            "4-16 m: mgmcmmmmmmmmmmmtmmm\n" +
            "3-5 g: gggbsg\n" +
            "9-15 l: dnslgllwlflmlllllll\n" +
            "3-4 h: mhhh\n" +
            "3-5 z: vkjzlzzvrztwg\n" +
            "11-12 q: qqqqqqqqqqqq\n" +
            "5-10 p: xpxprppppgzppp\n" +
            "1-4 z: kzzhzszzzzzzzz\n" +
            "2-7 j: nsjfszt\n" +
            "8-13 j: qtrjfmbjfswrj\n" +
            "2-10 s: ssscwcsnsssrt\n" +
            "1-12 w: zwwwwwwwwwwx\n" +
            "2-4 p: ppgvf\n" +
            "2-3 n: hnnxmgtchqwgnfx\n" +
            "11-12 z: bfzlvgdzpfzzzgvhz\n" +
            "1-6 d: czqqdjrxs\n" +
            "6-7 r: rrrrrkz\n" +
            "4-7 d: hxdzddvq\n" +
            "2-4 g: slwgs\n" +
            "13-14 f: mqfhrlftvvfkff\n" +
            "12-14 d: ddddddddddhqdc\n" +
            "1-3 f: ffzff\n" +
            "4-5 r: mrrrkrrrrrrkr\n" +
            "3-4 m: mmwl\n" +
            "2-5 j: jljjsjdj\n" +
            "4-5 f: fkfdf\n" +
            "16-17 s: dzdsrsgmsjffsnssls\n" +
            "10-17 f: fffffhffffhffffff\n" +
            "8-10 v: fvvvvvvvvz\n" +
            "4-9 n: nnnpsnjstl\n" +
            "8-11 x: xxzdxfjczxx\n" +
            "4-10 k: nrkxhfzspmfpzcl\n" +
            "7-10 x: pxxjlcbtsjxdc\n" +
            "1-14 s: fsszssssssfsssss\n" +
            "5-7 d: ddgdgdvddd\n" +
            "2-11 t: jttpshfcmlt\n" +
            "1-3 v: pvdv\n" +
            "5-7 x: xxkxxxx\n" +
            "13-14 d: ddddxdvdppdcrdhk\n" +
            "2-6 h: hhmhpc\n" +
            "6-11 g: jxhsggmgcrp\n" +
            "13-16 r: krrrnccjrrtrtrrlprrr\n" +
            "3-4 f: ffff\n" +
            "5-7 t: ttttttttttttt\n" +
            "5-7 d: ndddjdw\n" +
            "7-12 w: wgjwwbwcxfww\n" +
            "2-6 s: sxsssbs\n" +
            "12-14 l: xlxslmmjpvmzll\n" +
            "4-6 h: hdhhhhdhkch\n" +
            "9-11 j: jjjjjjjjjjj\n" +
            "6-8 d: dddddddn\n" +
            "5-6 b: bbbbsnbbbbb\n" +
            "1-8 h: hhhhhhhhhh\n" +
            "5-11 p: ppppppppppp\n" +
            "11-12 d: dddddddddddk\n" +
            "1-2 b: bbpbb\n" +
            "2-8 j: jjhhjzjjt\n" +
            "5-6 k: kfkjkk\n" +
            "3-5 j: kgjjjjqnjcfmjjrc\n" +
            "2-5 l: jtmzhlcs\n" +
            "3-6 v: vvvvvvv\n" +
            "15-16 v: vpvvvvvvvvjvvsvvvvvv\n" +
            "15-16 h: hhhhhhhhmhhhdhhh\n" +
            "2-3 k: ksdg\n" +
            "7-11 b: dbhbbbbbhbbrb\n" +
            "4-14 k: kkkknkkkkkbtkkk\n" +
            "5-6 j: smdndsgfm\n" +
            "2-3 c: sccc\n" +
            "10-15 w: bwwwbwwwcwwlwwpwwwww\n" +
            "3-6 w: wwwwwww\n" +
            "14-19 s: jqdgjszsssssdrssjszs\n" +
            "5-10 p: vpppbppppp\n" +
            "4-7 p: zcpltzbsjmcgpv\n" +
            "2-8 j: tfjjjjjnprj\n" +
            "14-15 m: mmmmmmmmmmmmmhqm\n" +
            "1-6 t: pttttct\n" +
            "9-10 n: qnbnzxjfnnkb\n" +
            "5-6 v: vvvvjvv\n" +
            "7-8 v: qvvbvpvvvf\n" +
            "2-15 s: sjsssssssssssstss\n" +
            "7-10 b: bvbbbbnbbbbb\n" +
            "13-14 b: bqbbbjqbbbbbtq\n" +
            "3-7 k: cltbmkkb\n" +
            "8-9 c: mlscsmqccfmccszsslck\n" +
            "3-4 k: kklckk\n" +
            "5-7 c: cccmclg\n" +
            "5-7 d: dnddddd\n" +
            "1-5 f: xfffbffffffffff\n" +
            "13-15 n: nnnnnnnnnnnnnnqfnn\n" +
            "3-6 t: ttttqztttcttt\n" +
            "3-4 s: ssnws\n" +
            "9-11 f: bcvkzrdrcffgzjgvf\n" +
            "3-10 r: rrrdrrqrrrrrr\n" +
            "3-6 h: bbqhkh\n" +
            "3-8 n: nngnwthw\n" +
            "1-11 x: ffqbbnxcpkrlzhm\n" +
            "3-4 b: bbbbnnb\n" +
            "5-6 f: lfdwqjffmj\n" +
            "7-16 v: vvvvvvvvvvvvvvvvv\n" +
            "13-15 m: zmmmzmmmmmmmmkmrmmmm\n" +
            "1-2 r: rrrr\n" +
            "12-14 d: dkdddddddddddcddd\n" +
            "14-15 r: crlrtjkrrnhqrrr\n" +
            "5-9 w: xjjwpcpfffchxtww\n" +
            "15-16 d: jdcchsgdjtjdcxdrlwx\n" +
            "9-15 p: cpmpppprpnpppsp\n" +
            "6-7 w: jlqkwww\n" +
            "1-12 p: wpfqzppptpflp\n" +
            "4-14 x: xxxxxxxxxxxxxxxxxx\n" +
            "1-4 z: xzzjz\n" +
            "2-10 t: zvbnlwltbkvvcf\n" +
            "5-9 v: vpvvvvfvvvvv\n" +
            "2-12 l: lllllllllllllllll\n" +
            "2-6 w: wmcwzpvxqsbxrrw\n" +
            "11-12 l: lldlllllllrllgll\n" +
            "9-13 h: hhhhhhhhdhxhrhh\n" +
            "6-9 x: xxxzxxxxxxxx\n" +
            "1-15 x: vcsxxxgxxxxwxxbbxx\n" +
            "7-12 d: fmddcdfndddddkdnrgt\n" +
            "12-14 x: wlmbpdxxrxbxdxg\n" +
            "5-9 l: gnllscnsz\n" +
            "4-5 j: jjjjj\n" +
            "6-10 q: kvctnxpqhqfhjb\n" +
            "6-8 q: vqqnqcqpqq\n" +
            "2-9 k: mvxsbrxzr\n" +
            "10-11 c: lbcgbpsxhcc\n" +
            "9-17 x: xkdpklsvxqlkvrlvx\n" +
            "3-14 j: trjcmjzjqkbjjj\n" +
            "7-8 k: kkkkkkhfg\n" +
            "1-3 f: pfdf\n" +
            "9-12 s: glcjzdmllprrrxmdds\n" +
            "9-11 b: bwbbbbbbbbqb\n" +
            "2-14 f: kzfffbzfhfffflf\n" +
            "5-7 n: ngnnnnn\n" +
            "6-10 t: tttttrtttjtt\n" +
            "7-8 f: fvffzfpff\n" +
            "3-5 h: jbhkx\n" +
            "9-11 b: qckbnjtbcbb\n" +
            "12-15 m: mmmmkmmmmqmmmmjxm\n" +
            "9-11 c: cdckczpcccc\n" +
            "1-3 v: wzxq\n" +
            "8-11 q: qhqqqqqlqqnqq\n" +
            "4-9 j: mpjjqsdsj\n" +
            "13-17 s: sssssssssssssssss\n" +
            "4-7 x: knbxqrxxzl\n" +
            "15-17 m: mmmmmmmmmmmmmmmmmmm\n" +
            "6-10 w: wxnwfhwqdd\n" +
            "9-11 r: crrrrcrnrrwrrmrrrm\n" +
            "9-15 l: klflxlcllldllllll\n" +
            "1-4 n: vpnznn\n" +
            "2-4 k: cjkg\n" +
            "7-8 m: xqmmrmmjjshmfm\n" +
            "4-6 f: sfffff\n" +
            "2-7 l: mltmmnldsnnl\n" +
            "5-6 j: tjjdjxjjbs\n" +
            "4-5 p: ppmnp\n" +
            "2-3 b: bzrb\n" +
            "5-17 h: dmpdgxthrcppfznbhchw\n" +
            "3-4 p: pppp\n" +
            "3-5 v: vvhvvr\n" +
            "9-10 g: gflzqwbvgsgnbzngmgr\n" +
            "8-17 z: xpvzsrhgzqtdcfjzl\n" +
            "1-4 x: khxjxxvd\n" +
            "3-4 z: czzz\n" +
            "10-12 m: zjzcmmpxmjxmxzm\n" +
            "7-9 k: kkkkkkkktkzkkk\n" +
            "16-17 d: ddrdgdxdddddgddwmd\n" +
            "2-16 f: xmsflgsvfwnfmxwnnmg\n" +
            "4-12 b: ltbkbqbbbbbc\n" +
            "12-14 t: tctlnvtjttsgztthtxtt\n" +
            "9-14 x: xxxgpxvlkxdxdrxxrxwx\n" +
            "15-17 s: xsssssssssssssvgw\n" +
            "10-16 q: hqqpqxjqbsxqfqbm\n" +
            "4-5 v: vvvnvvvttv\n" +
            "15-16 v: rwshvltmvgvcvpvv\n" +
            "4-5 j: jjjjjjjj\n" +
            "3-5 w: jwfwp\n" +
            "4-5 m: nddmm\n" +
            "10-13 t: rtttnttttttttj\n" +
            "14-17 l: llllllllllllltlcnl\n" +
            "7-16 p: crjhtmpppgkpvgnpt\n" +
            "6-9 b: bbfbbhbfgdrb\n" +
            "1-2 q: qkqq\n" +
            "17-20 f: hwcftkmtzhftmnfwfsdf\n" +
            "2-4 w: wjtww\n" +
            "10-11 p: pppppppppppp\n" +
            "5-12 l: dntvlnljwkkldgp\n" +
            "3-4 s: gmkvlqxsx\n" +
            "8-10 m: qmmmmmmmmm\n" +
            "12-14 p: gtbnfmlvtkppwp\n" +
            "7-8 t: ttttttvs\n" +
            "12-18 j: jjjjjjjjjjjjjjjjjb\n" +
            "5-7 p: tfrppwpcpppp\n" +
            "11-13 h: hthhhhzfbhhhdhhph\n" +
            "1-7 n: ncgsvwvlvwlhbtmnnnpx\n" +
            "10-11 j: djjbsjljjxf\n" +
            "5-12 n: cnjqkknnnnmjnq\n" +
            "18-20 z: zzzzzzzzzzzzzzzzzbzp\n" +
            "2-5 m: kphbm\n" +
            "12-13 g: tzrqwrjgzkxgg\n" +
            "8-9 w: mwwwkwwwww\n" +
            "2-6 j: jbxjjzjjjjj\n" +
            "9-10 j: jjjjjjjjznj\n" +
            "5-6 j: jjjspjj\n" +
            "8-18 g: jggmgpfggbvggvgggggl\n" +
            "3-5 n: nnxnh\n" +
            "3-18 n: nnlnnnnnngnnnnnnnhnn\n" +
            "6-10 r: rcrctghspmrrbrcrrrrq\n" +
            "18-19 s: sfxqssssgssscxsdrss\n" +
            "7-10 b: pbbbbbbgvbzbbz\n" +
            "15-17 m: mmmmmmmmmmmmmmhmmm\n" +
            "4-11 s: sssgssssssssssssxfss\n" +
            "7-9 g: ggtgggggg\n" +
            "4-8 w: wwwwwwwt\n" +
            "17-20 p: pppppppppppppppppppn\n" +
            "2-5 w: hdxrw\n" +
            "9-18 c: cccccccccwcccccccc\n" +
            "1-9 l: qllllllllllllll\n" +
            "15-16 g: ggggggggggggggnj\n" +
            "8-9 s: sjszkrhsss\n" +
            "12-18 g: ggggggggggggggggggg\n" +
            "5-6 s: ksnsxspsw\n" +
            "4-8 p: pppbpppcppppp\n" +
            "4-10 f: fffffffffff\n" +
            "1-2 d: dqdd\n" +
            "7-8 w: wwjwvhvcwbwww\n" +
            "3-5 h: xghfhzhqw\n" +
            "4-5 q: qqqzpw\n" +
            "5-9 q: fxkrhqrjq\n" +
            "2-4 m: mmjm\n" +
            "1-4 p: wpmg\n" +
            "7-13 n: nnnqfdtnnnnftnlnnn\n" +
            "2-11 w: vwphpjskljxgqsgqzph\n" +
            "2-4 w: wwwwgfkmpcf\n" +
            "6-10 w: htgtkwwrmwvgrdmkzt\n" +
            "3-4 s: sssstss\n" +
            "11-20 l: dqlqmkllqclbmzklllrt\n" +
            "1-6 g: gfgcwgvzkrhgjslg\n" +
            "2-13 j: jjjszjxjljjjjqjjvjjh\n" +
            "4-19 q: qqqlqqqqqqqqqqqqqqfq\n" +
            "11-14 j: jbjjjjjjjjrjjp\n" +
            "10-11 f: fpffvfffspvkf\n" +
            "4-5 v: vhvlvhgh\n" +
            "6-8 h: nsfklqhtxg\n" +
            "2-3 z: czwnzzp\n" +
            "1-10 c: wcmvcrcmjmcmbcckfcdc\n" +
            "2-4 f: hzbrjqqntbbffbfl\n" +
            "2-5 b: bzmbwztrb\n" +
            "7-9 z: bscfzxzxz\n" +
            "13-14 z: zzzzznzzzzzzbn\n" +
            "3-7 t: rlxttrcmfttlt\n" +
            "4-6 h: rldcbhx\n" +
            "11-12 g: vfgfdgffbrrg\n" +
            "1-10 s: ssssssssjsss\n" +
            "7-13 k: dqbklkhvlgphjqhvgc\n" +
            "8-18 x: xxxxdxxxxxxxxxxxxzxl\n" +
            "1-3 x: xxxx\n" +
            "11-12 z: ttzhvzzzxkzzzzgz\n" +
            "5-7 h: hjmhhhhh\n" +
            "10-12 l: lllllllpllllwmwwb\n" +
            "2-6 j: hfjqlm\n" +
            "6-9 n: mnnqfnpkw\n" +
            "7-8 c: cckcqchscc\n" +
            "4-5 q: qqqqq\n" +
            "11-13 d: dddddddjddddgd\n" +
            "3-11 q: qvqlqqqqlknnqhq\n" +
            "1-4 h: hnphh\n" +
            "9-15 f: ffffffffffffffffffff\n" +
            "4-7 p: pxpvbpcz\n" +
            "9-14 g: ggggggggwgggggg\n" +
            "1-2 w: wwwwwwwwww\n" +
            "4-5 g: ggcgggvg\n" +
            "11-15 k: kkkgtkcjmwkrkkkkkk\n" +
            "3-4 w: wzww\n" +
            "8-10 k: kkkkkkkwjqtkkkkkkkk\n" +
            "5-6 n: djnfkmzzbc\n" +
            "12-18 x: jxxnxhqxxxxsxxxbxxxx\n" +
            "13-14 p: hbmspppspppkgp\n" +
            "15-16 d: dtddddddddddddpkd\n" +
            "4-6 q: bvqqcpq\n" +
            "2-4 h: dqhsjpp\n" +
            "10-11 l: llllllklwll\n" +
            "4-5 h: dhhcdh\n" +
            "3-5 t: mvntxdsxftt\n" +
            "5-9 w: wxpqwwqwjf\n" +
            "14-15 c: cccccccccccccccc\n" +
            "6-8 b: bbtbbdbwb\n" +
            "4-7 g: gdpqgrj\n" +
            "1-6 p: qppppppp\n" +
            "1-14 s: sqssssbrszsskmss\n" +
            "7-9 n: nnnnnnvsn\n" +
            "4-7 r: nrltrrhndcbrr\n" +
            "8-18 d: dddddddpdddddddddfdd\n" +
            "1-3 b: bbbbb\n" +
            "6-7 f: fpfplqf\n" +
            "2-8 j: jjjjjjjsj\n" +
            "3-5 h: ndhwxnb\n" +
            "4-5 z: zzcztzv\n" +
            "5-6 c: ccccck\n" +
            "3-4 q: qjqqqqq\n" +
            "4-19 q: nsqqgqpgmjsmbkpzwvl\n" +
            "13-15 r: rrrrrrrrrrrrrrrrr\n" +
            "6-12 k: kckvkkhkfbkkkkkkr\n" +
            "3-5 x: xxxxsxx\n" +
            "3-4 s: ssff\n" +
            "2-7 l: pgwllllhlxwl\n" +
            "8-18 z: zzzzzzzzzzzzzzzzzz\n" +
            "1-11 c: fhhcjcchrlxcpcc\n" +
            "3-4 w: zhcjwjnwgwg\n" +
            "1-7 x: zxlpxmxt\n" +
            "12-13 k: jskdrkmhkkkndk\n" +
            "1-8 x: xmpwwvrx\n" +
            "10-12 r: kprvkppwczjt\n" +
            "1-12 b: sbbbvgbbzgbtbklsbb\n" +
            "1-2 z: zzgqpwhzrhnrgjrgrstz\n" +
            "9-11 s: ssssxssssss\n" +
            "3-10 k: sbksdgcrkkxfgc\n" +
            "7-8 n: nnnnnnzf\n" +
            "13-14 j: jjjjjjjjjjjjjj\n" +
            "3-4 f: fmff\n" +
            "13-14 k: nkkkkkkkkkkkkk\n" +
            "2-3 w: zbtww\n" +
            "1-5 k: kgmkkrckdp\n" +
            "4-5 p: xphlp\n" +
            "3-4 k: tzzh\n" +
            "2-6 s: jssvsxdsszsthspslztk\n" +
            "1-3 z: mzzzqzzz\n" +
            "5-7 h: hkhhwgwlchnh\n" +
            "8-14 v: dvvvhggtsvdwgx\n" +
            "3-8 d: dxdrkjcd\n" +
            "2-4 d: pkmb\n" +
            "8-11 b: bbbbbbbmbbkbbb\n" +
            "3-12 j: wxljjrjjjjhzj\n" +
            "5-17 c: wbnpcnngzcgcgbqwvkh\n" +
            "2-6 q: sqlbhq\n" +
            "1-3 n: nlbqgnhcnnznj\n" +
            "2-3 k: gkncgkn\n" +
            "4-6 g: gwxglggzhnq\n" +
            "3-14 j: dgjcfxrjcgwjmjdmggk\n" +
            "2-3 z: qvnrlzs\n" +
            "11-12 k: kdtwlzkjfdkkfkn\n" +
            "15-18 b: bqpxdxbbhkbnfdbfpb\n" +
            "5-15 j: jjjjgjjrjjjjjmmjjjj\n" +
            "8-13 t: tthtpttttmtktttt\n" +
            "6-8 f: wxbpffcf\n" +
            "8-9 b: bbbbbbbwr\n" +
            "8-14 l: xmlrtbphkjrxrg\n" +
            "15-18 x: qxxxlpxxmxxhmmxxxx\n" +
            "7-11 c: cccccsclcrc\n" +
            "1-4 k: kkkkkk\n" +
            "3-4 j: jdqq\n" +
            "11-15 b: vgfqbwsrkhgjhjv\n" +
            "13-16 k: kkkkkfkkkkckkkkkkk\n" +
            "18-20 b: lwwgrrbtwbcvdhbwbmbf\n" +
            "7-12 m: mmmmmmmmmmmmmm\n" +
            "2-12 l: pllndrxbzqzlmzstmbvw\n" +
            "3-14 r: rrrrrrrrrrrrrrrrrrr\n" +
            "1-16 p: ppppppppppppppppppp\n" +
            "5-9 x: mtbxxxjxxxxd\n" +
            "2-4 r: rrrrrrrrrr\n" +
            "3-4 k: kfkz\n" +
            "3-5 m: mgmmmm\n" +
            "11-12 l: blcpjbfvzjll\n" +
            "2-4 z: tzzzd\n" +
            "5-9 z: zzzzqzzzrzjzzzzz\n" +
            "10-14 m: mmmmmmmmmmmmvcmmm\n" +
            "2-7 w: jwchkdws\n" +
            "12-14 p: mdpppjpppppppppppr\n" +
            "15-18 v: vvvvvvvvvvvvvvtvvcv\n" +
            "4-10 p: pppfmbkhqppkvzpp\n" +
            "3-17 p: ppppppjppppppppppppp\n" +
            "3-6 r: cjvklrqrnhkk\n" +
            "1-3 s: sssss\n" +
            "2-6 d: dqddctdjd\n" +
            "12-16 k: kkprkzdksmkbkfxd\n" +
            "8-13 g: pggggggzwgggwgggmg\n" +
            "13-16 b: sbwbbpbhbbbbdbbgb\n" +
            "10-14 c: ccccccccccccccccc\n" +
            "4-8 j: cxkxmzcrsnvbkfvmlk\n" +
            "5-13 l: lmdnlnkbtspvll\n" +
            "3-4 g: ggmgmmhwfmg\n" +
            "5-7 d: ddddjdp\n" +
            "11-15 v: vplvcvvdvhvmvtv\n" +
            "10-12 r: rhrrrjrslrrnrqrrrzrn\n" +
            "2-6 x: xhxxxxxx\n" +
            "5-10 s: zmrkslzcdsrssfsssss\n" +
            "5-7 r: rrrrrrr\n" +
            "3-4 g: ggpx\n" +
            "14-15 s: sssssssssssssmb\n" +
            "1-5 w: smclhnwxff\n" +
            "4-9 l: lllcllllqvlllll\n" +
            "1-4 s: lhpd\n" +
            "12-14 b: cwbdzbbbbdbfqc\n" +
            "5-13 b: qtbsqbvjbcxbkznrlb\n" +
            "10-12 f: fffpfffffxfqffffff\n" +
            "15-16 x: xkxdqrxlwxxvxtxx\n" +
            "14-15 p: ppjpgdppppppppgpp\n" +
            "10-16 n: nnwnnnnnnnrqnnnn\n" +
            "5-7 k: kwwzqdn\n" +
            "2-3 m: mchvnq\n" +
            "6-10 h: vhhxzphthw\n" +
            "5-6 r: slpcrr\n" +
            "17-18 b: bbbbcmbbbbbbbbbbpzbb\n" +
            "3-5 s: wfscss\n" +
            "9-12 r: rfjrrtrrrrkrr\n" +
            "1-8 t: tstztmttgtttfvt\n" +
            "8-9 f: fffffffjnff\n" +
            "7-13 l: lkxclrlgldxllcll\n" +
            "10-12 s: bssssdssbsxc\n" +
            "8-12 t: tttttttwtttttt\n" +
            "3-11 d: ndrndqqzqhdnjf\n" +
            "1-10 g: xgqgggqggfmgggggggmg\n" +
            "8-9 x: kttxbdnxxxcfjxxrxgxx\n" +
            "4-10 n: ndjrqmcxnh\n" +
            "12-13 c: txpwlvzhxhcwbpg\n" +
            "8-9 z: crsqsztzz\n" +
            "5-6 b: vbwbjb\n" +
            "4-5 v: vvvvv\n" +
            "2-6 d: tdsddddx\n" +
            "4-10 r: hzqzrrnwrrhrrfrfwrr\n" +
            "11-18 g: ggggggggggggggggggg\n" +
            "1-7 z: zhcppxz\n" +
            "7-9 r: rrwrrrrrr\n" +
            "1-9 l: hlllllllqllpllllllvd\n" +
            "1-4 g: jklqjgvtxsggfjggg\n" +
            "2-18 m: mmqmmmjkmmmlkmmmlvmm\n" +
            "1-8 w: kwgwxzshwwwc\n" +
            "6-7 f: fffzfgk\n" +
            "6-8 t: ttttthtcttk\n" +
            "3-14 s: hsszwzdxkhsphrtrcbs\n" +
            "4-10 l: lllllbllllll\n" +
            "3-8 g: gggdgggkj\n" +
            "1-4 x: xxxcx\n" +
            "3-7 k: tqhknrkxjxqv\n" +
            "11-19 p: pwwppgsztplgssgtpsp\n" +
            "11-12 k: kkkkkkkkkklgkkk\n" +
            "4-16 h: tnhhcgldlnzngvhb\n" +
            "8-11 w: znwwwwwwwwwwww\n" +
            "8-9 m: mbtmmmccjvmtm\n" +
            "14-15 l: lllllllllltllfw\n" +
            "11-16 z: kfslzzwszdmsnptcz\n" +
            "5-6 g: qgggggk\n" +
            "3-8 k: kkmdkwkd\n" +
            "9-14 v: vvvvvvcvnvvvxwvfvv\n" +
            "3-7 v: vvtvvvcmvvvvxvvvv\n" +
            "6-7 l: dnfjfzfhhn\n" +
            "9-10 g: mtzwcwgfjgshqg\n" +
            "2-9 s: bsgcgjrqs\n" +
            "3-4 c: ccpc\n" +
            "9-14 n: nnnnnnnnnnnnnnknnnn\n" +
            "4-5 p: tppxsp\n" +
            "4-6 x: xmxxnxxw\n" +
            "3-4 m: mmmm\n" +
            "15-16 s: swshctdsksqgcsqsr\n" +
            "2-4 x: xxxxxx\n" +
            "6-7 h: hhvhhhh\n" +
            "8-15 n: nnmvfnhnlndnwgjthmb\n" +
            "4-5 z: fvzzzw\n" +
            "1-12 m: wmjwgmmlmmmm\n" +
            "7-16 n: xhnxjkjprznthqmdnwnl\n" +
            "6-9 b: bbbbbbbbb\n" +
            "17-19 d: ddwdlddkrgdkdddpqdj\n" +
            "6-9 b: bbbbbbbbbb\n" +
            "7-19 l: llvllllllclllflllll\n" +
            "7-9 h: lhhhhhfhhhh\n" +
            "7-10 m: hsdgdmmqqncdcgfxpb\n" +
            "7-8 h: hqzcmvhw\n" +
            "3-7 l: clkllltlwlp\n" +
            "1-2 g: gsgggggqgg\n" +
            "6-8 j: qjjqqcjjjjtjs\n" +
            "11-14 r: nrlhdrrlbrrxgg\n" +
            "3-10 s: tsxfscsfsws\n" +
            "6-7 t: tstttdtbt\n" +
            "6-7 r: rrcxrplkrnrrrbrpl\n" +
            "3-11 b: pbwvpbkbzdbwbvlb\n" +
            "5-11 d: wgwhfxtjmdfd\n" +
            "7-12 m: chmmmrmrmxmqjcpmb\n" +
            "1-2 n: nntnnn\n" +
            "4-12 l: lllllllllllnllll\n" +
            "4-5 c: ccchc";

    public int getNumberOfValidPasswords() {
        String[] rulesAndPasswords = inputData.split("\n");
        int validPasswords = 0;
        for (String entry : rulesAndPasswords) {
            if (isPasswordValidRuleTwo(entry)) {
                validPasswords++;
            }
        }
        return validPasswords;
    }

    /**
     * Determins if the given entry (rule-password is valid)
     *
     * @param entry eg: 8-9 z: crsqsztzz
     * @return true if valid, false otherwise
     */
    private boolean isPasswordValidRuleOne(final String entry) {
        String[] entryChunks = entry.split(" ");
        String[] occurancesChunks = entryChunks[0].split("-");
        int minOccurances = Integer.parseInt(occurancesChunks[0]);
        int maxOccurances = Integer.parseInt(occurancesChunks[1]);
        char letter = entryChunks[1].charAt(0);
        int occurances = 0;
        for (int i = 0; i < entryChunks[2].length(); i++) {
            if (entryChunks[2].charAt(i) == letter) {
                occurances++;
            }
        }
        return minOccurances <= occurances && occurances <= maxOccurances;
    }

    /**
     * Determins if the given entry (rule-password is valid)
     *
     * @param entry eg: 8-9 z: crsqsztzz
     * @return true if valid, false otherwise
     */
    private boolean isPasswordValidRuleTwo(final String entry) {
        String[] entryChunks = entry.split(" ");
        String[] occurancesChunks = entryChunks[0].split("-");
        int positionOne = Integer.parseInt(occurancesChunks[0]);
        int positionTwo = Integer.parseInt(occurancesChunks[1]);
        char letter = entryChunks[1].charAt(0);
        int occurances = 0;
        if (positionOne > positionTwo || positionTwo > entryChunks[2].length()) {
            return false;
        } else {
            if (entryChunks[2].charAt(positionOne - 1) == letter && entryChunks[2].charAt(positionTwo - 1) == letter) {
                return false;
            } else {
                return entryChunks[2].charAt(positionOne - 1) == letter || entryChunks[2].charAt(positionTwo - 1) == letter;
            }
        }
    }
}
