package com.ss.aoc;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class Day06 {
    private String testData = "abc\n" +
            "\n" +
            "a\n" +
            "b\n" +
            "c\n" +
            "\n" +
            "ab\n" +
            "ac\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "b";

    private String inputData = "mswxhfpl\n" +
            "xmhulfp\n" +
            "jhglrxfvmp\n" +
            "xtldhmpf\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "lc\n" +
            "c\n" +
            "\n" +
            "zxe\n" +
            "ex\n" +
            "oxncuje\n" +
            "vdex\n" +
            "devx\n" +
            "\n" +
            "xjylztwnkbma\n" +
            "apxzvjlwnbdyk\n" +
            "zlnbrkyagwjx\n" +
            "ykslxwbjuzang\n" +
            "wjkbylazxne\n" +
            "\n" +
            "aekysof\n" +
            "ecfokmdaysl\n" +
            "ykiosefa\n" +
            "oxsugykeaf\n" +
            "fstyoake\n" +
            "\n" +
            "svzgnfiujobmc\n" +
            "kjlvfbnwimuzdqtgsec\n" +
            "cgijufnsbmzxv\n" +
            "csfnzvujmigb\n" +
            "\n" +
            "jzofxqebrk\n" +
            "zmverjxoafush\n" +
            "ozclfjbierx\n" +
            "jforizlex\n" +
            "\n" +
            "cedziyl\n" +
            "lnemy\n" +
            "\n" +
            "oujdnhgwlqfbmpcrevktaizs\n" +
            "covqbthupgradfnijslexwk\n" +
            "\n" +
            "eawjhlxrtc\n" +
            "ahjlwexcr\n" +
            "\n" +
            "yhnidq\n" +
            "ehznqy\n" +
            "qhyn\n" +
            "hcqny\n" +
            "qywnchd\n" +
            "\n" +
            "skzfnylhmdqcgjoiuv\n" +
            "zwlujnyfismkgdh\n" +
            "nyfxlmiuwdgzkj\n" +
            "jnekmgtdpfuzilbr\n" +
            "\n" +
            "gecslpwytzojbv\n" +
            "retwyjsaclbdovzp\n" +
            "cjuvysbwomlphqnkxz\n" +
            "\n" +
            "xtqpviho\n" +
            "gqvpiothzx\n" +
            "thfcoiqvprxk\n" +
            "\n" +
            "jthwqvmbodsi\n" +
            "ojdhilmqstv\n" +
            "\n" +
            "cflmw\n" +
            "wxvmct\n" +
            "aihergjyzdqob\n" +
            "\n" +
            "zmesxd\n" +
            "wjcx\n" +
            "gcbx\n" +
            "xpbv\n" +
            "\n" +
            "sx\n" +
            "ph\n" +
            "fdxg\n" +
            "fws\n" +
            "fa\n" +
            "\n" +
            "pbjtdyizfqnrgloucmax\n" +
            "jdfmibnyuzcxtavqrpgsl\n" +
            "\n" +
            "j\n" +
            "vynjf\n" +
            "kueiaqgod\n" +
            "pfmxby\n" +
            "\n" +
            "vdjbnwz\n" +
            "zwasclpx\n" +
            "wfzr\n" +
            "\n" +
            "pf\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "mch\n" +
            "h\n" +
            "w\n" +
            "\n" +
            "qkeadjmtczxrps\n" +
            "cxrmjkaqzpdtes\n" +
            "esctpmdjxkzqar\n" +
            "ekzdsmtxjqcpbwfar\n" +
            "\n" +
            "edvrzgwkcs\n" +
            "wsvdzkgec\n" +
            "\n" +
            "rsu\n" +
            "rloufsk\n" +
            "utrs\n" +
            "urs\n" +
            "\n" +
            "zprftcsdnqxkblyuhvje\n" +
            "kvdrtajflzeqxhysbp\n" +
            "\n" +
            "mrf\n" +
            "pfrm\n" +
            "urf\n" +
            "nfo\n" +
            "\n" +
            "rcympeozltx\n" +
            "uztmycxl\n" +
            "wutxyzmcl\n" +
            "dvwcztxylbm\n" +
            "qxjhzamykltc\n" +
            "\n" +
            "hoxcl\n" +
            "lxhco\n" +
            "xhclo\n" +
            "ohlcx\n" +
            "\n" +
            "eybugcnido\n" +
            "oigyeunbdc\n" +
            "gnieobcduy\n" +
            "codnibeugy\n" +
            "\n" +
            "zvqjxpwakbdtygemulifhrsoc\n" +
            "qoxapdubyhmcgkeftswrvlizj\n" +
            "tysoxrkpbfhvmdlzaeiujqcgw\n" +
            "uxeiclqrvwpmhatjskfodgzyb\n" +
            "iudalfpszevwjtxcbmoghkrqy\n" +
            "\n" +
            "o\n" +
            "r\n" +
            "k\n" +
            "o\n" +
            "r\n" +
            "\n" +
            "i\n" +
            "iqs\n" +
            "i\n" +
            "\n" +
            "ntbydrsj\n" +
            "drvpnfmbgxowi\n" +
            "rbtdn\n" +
            "reynubd\n" +
            "dnabrz\n" +
            "\n" +
            "wsmlkzp\n" +
            "klmwpsz\n" +
            "\n" +
            "cdpkmfyotaxl\n" +
            "hcgipntkua\n" +
            "\n" +
            "wdphxlyagcvtf\n" +
            "fahvdtwgexypj\n" +
            "fwadhugxivtyp\n" +
            "whpdgvxyrifta\n" +
            "xadtyvhpfwg\n" +
            "\n" +
            "nzliogx\n" +
            "e\n" +
            "je\n" +
            "\n" +
            "c\n" +
            "e\n" +
            "\n" +
            "yqlemtbvrohpk\n" +
            "zmpbvthoqunkrle\n" +
            "tblrhmpkeoqv\n" +
            "\n" +
            "qido\n" +
            "mdktovwalfju\n" +
            "sybod\n" +
            "qdboi\n" +
            "dnbog\n" +
            "\n" +
            "qpgj\n" +
            "dypie\n" +
            "jaq\n" +
            "yf\n" +
            "tusvwmncr\n" +
            "\n" +
            "knwsuztcfrqyvjb\n" +
            "edtrazumclkjof\n" +
            "\n" +
            "vo\n" +
            "vo\n" +
            "v\n" +
            "cvmf\n" +
            "\n" +
            "cfxyhjorspzdbqnvwa\n" +
            "yvbhnqusrcpxawfjzdo\n" +
            "bzqnwfajcovyxsphrdk\n" +
            "\n" +
            "kczjha\n" +
            "tzqalgvpx\n" +
            "kauz\n" +
            "nawuzfeih\n" +
            "\n" +
            "gwknqytrvpusc\n" +
            "gnpucwskqv\n" +
            "qsvunkgwpc\n" +
            "\n" +
            "cfxuqsywnbrphelktmi\n" +
            "qrfhskmluetxwnbicy\n" +
            "ymtbeckhsjfvgnuzwxqlrd\n" +
            "tuynrwxckehqlbomsf\n" +
            "\n" +
            "mzkyn\n" +
            "uyoxtkem\n" +
            "rselkop\n" +
            "vigbhwfdqackj\n" +
            "\n" +
            "hzoditwmkseaqvr\n" +
            "rdkstohmaqvez\n" +
            "pikrasoehmqzdv\n" +
            "hyovremdqsucknzab\n" +
            "\n" +
            "bnjywtdxvoq\n" +
            "cdbqoxwrt\n" +
            "etmxpdboqkwhuzl\n" +
            "xqbwotadn\n" +
            "xsnqbwvodyt\n" +
            "\n" +
            "fxqkozj\n" +
            "rtnslf\n" +
            "\n" +
            "dsknxltjremvzo\n" +
            "nlozxmdvkrtejs\n" +
            "mvoerklsidjzxawtn\n" +
            "nzkmsrxtldoegvj\n" +
            "\n" +
            "l\n" +
            "blc\n" +
            "l\n" +
            "\n" +
            "mbhdfyvxzciou\n" +
            "oyhbiuvcmfdzx\n" +
            "cixfdvymhuzob\n" +
            "difuyzobhvmcx\n" +
            "dxycmfuizbovh\n" +
            "\n" +
            "fujhbprknwvltcm\n" +
            "njvrxsfbdqagecoumliz\n" +
            "\n" +
            "fctvyqsoulzwbmdparigx\n" +
            "luhkiejfgyoqzrawndcmps\n" +
            "\n" +
            "fbdxwpecovh\n" +
            "pebxdhvfwoc\n" +
            "edofpxwvcbh\n" +
            "\n" +
            "ptesvjkbdawr\n" +
            "zxpwuhrelfybnjv\n" +
            "regdowbpvcj\n" +
            "\n" +
            "t\n" +
            "q\n" +
            "nugiav\n" +
            "es\n" +
            "\n" +
            "h\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "rzbhp\n" +
            "czbhpnr\n" +
            "\n" +
            "ftovldbexga\n" +
            "lobgkcxqdrejy\n" +
            "\n" +
            "z\n" +
            "z\n" +
            "bz\n" +
            "\n" +
            "bigtxjsafzm\n" +
            "dlnzjukcxbvtwmp\n" +
            "\n" +
            "fp\n" +
            "fp\n" +
            "pf\n" +
            "\n" +
            "zxgovsrcfjutwqkelybpaimd\n" +
            "kgsujzbyqeiaxcmvotfdprwl\n" +
            "eqgmvoizprfsdlbnykuahcwtx\n" +
            "\n" +
            "axfcs\n" +
            "faxsc\n" +
            "\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "gjardhk\n" +
            "gymjrhf\n" +
            "rlohugbszpj\n" +
            "hrcqgxj\n" +
            "\n" +
            "kdyaqxzlp\n" +
            "kdypxaqlz\n" +
            "xadperlzyqk\n" +
            "dlpaykxqz\n" +
            "ydlpxzaqk\n" +
            "\n" +
            "bumwf\n" +
            "hmuwbf\n" +
            "wbumjf\n" +
            "wbufm\n" +
            "\n" +
            "gvtrbwyoemajicfqkpsznl\n" +
            "ntpjelqbrwosaygfkvcizm\n" +
            "joqrgykmftclnwiesvzabp\n" +
            "vacpqzebgytkiomnsrfjwl\n" +
            "bpklgfwonicthezvsmyjqra\n" +
            "\n" +
            "fyhblqmotxiav\n" +
            "vyziosltfbdnkxjquch\n" +
            "ilfbwxevoqtrhgy\n" +
            "nmxshlouqbiftyv\n" +
            "\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "\n" +
            "wt\n" +
            "rwt\n" +
            "\n" +
            "bdyqkonw\n" +
            "nzybwkxd\n" +
            "dwkbhyn\n" +
            "\n" +
            "yqvzrxgwhkapjfbtuocnmsei\n" +
            "pfnatxsmjeoqzuwygikrhvc\n" +
            "\n" +
            "ejsktcwgrhuf\n" +
            "irjhkzogfbepv\n" +
            "\n" +
            "nxqfubpw\n" +
            "fpnbwqurx\n" +
            "xunobqgfwp\n" +
            "puwqnfxb\n" +
            "nbgufxqpw\n" +
            "\n" +
            "cwyd\n" +
            "odwyc\n" +
            "dwcy\n" +
            "cdwy\n" +
            "cwbldy\n" +
            "\n" +
            "ftomgqcl\n" +
            "fomgtclq\n" +
            "fgmtlqczo\n" +
            "\n" +
            "lvxjqb\n" +
            "inldekpms\n" +
            "\n" +
            "gcprvyta\n" +
            "vtmypzrgaiqoswun\n" +
            "yxrgvbatp\n" +
            "gevatypr\n" +
            "\n" +
            "clmoytbvweaxpuhgzfdki\n" +
            "cpvzahbtxdiwlf\n" +
            "bzifpalhdxctwjv\n" +
            "atfbvxdpzlwhicn\n" +
            "pvflhxibtzsdcaw\n" +
            "\n" +
            "wcrvztqdlboyhajpsn\n" +
            "zcnrkvlpyqwbdjhotxas\n" +
            "nhlydqcvbirtpszjwoa\n" +
            "tdhlebrcfmzyqavponjws\n" +
            "\n" +
            "mibplyvrah\n" +
            "pyblgkriam\n" +
            "\n" +
            "ocyudmgxkelbznavf\n" +
            "msvgbzkoduahqecnwx\n" +
            "\n" +
            "hmcwetindlboqg\n" +
            "pmqesoxwbvfyndctjg\n" +
            "lwoktgnbdqzcrmeu\n" +
            "\n" +
            "dzkbgjcwripto\n" +
            "jigscwfptnv\n" +
            "pijcqmwgot\n" +
            "\n" +
            "ey\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "\n" +
            "sajmqc\n" +
            "jcaqs\n" +
            "\n" +
            "pbwcnxiksumzr\n" +
            "twuplsmrnbczxiak\n" +
            "muzxcpbdkwsinr\n" +
            "vzwspnrubkxcmqi\n" +
            "\n" +
            "ismvnoaxj\n" +
            "iajomvsnx\n" +
            "nosjavmix\n" +
            "jsoxvamni\n" +
            "\n" +
            "opvzkytiaslxc\n" +
            "ucoktzvyalpexis\n" +
            "oazstxklypivc\n" +
            "sokaiylvpcztx\n" +
            "\n" +
            "nvarkyce\n" +
            "ctxrjkyevb\n" +
            "ycrzevk\n" +
            "\n" +
            "gjtovuln\n" +
            "blujitongk\n" +
            "oltugnj\n" +
            "\n" +
            "bktapxzq\n" +
            "zktapqxb\n" +
            "tzaxbkqp\n" +
            "bxqazpkt\n" +
            "ptkebzaqx\n" +
            "\n" +
            "jd\n" +
            "qje\n" +
            "apcbl\n" +
            "\n" +
            "mavsrdnzwlkhjpbqxcg\n" +
            "qnbakvirdpmwgsxhjczl\n" +
            "qgamhlbojncdkyxpzevrws\n" +
            "kclvwnazrhjsgpbdmqx\n" +
            "ptfkzvmwsgdhaqxlrbnjc\n" +
            "\n" +
            "pkaywuzgvlbhf\n" +
            "wypbflhnxauvz\n" +
            "pzuhrgbdvalfwy\n" +
            "\n" +
            "jubkivaofsqcdrwynt\n" +
            "svogcltjufxznirqbkh\n" +
            "wftqnsivmrokjubc\n" +
            "yukepnbijtdcfqsovr\n" +
            "\n" +
            "jiehxtqmu\n" +
            "mjqeuxsthi\n" +
            "euqtixmhsj\n" +
            "ibemtdjquhx\n" +
            "jmetuxvqih\n" +
            "\n" +
            "pmatrxqlygbo\n" +
            "tygralmonqpx\n" +
            "ljkgmeoyraxpqt\n" +
            "\n" +
            "txilwvdspnukbr\n" +
            "wcimylaqr\n" +
            "\n" +
            "kzcygblopsftxu\n" +
            "fyupmztolxskgb\n" +
            "\n" +
            "khnoluj\n" +
            "oyngjhuq\n" +
            "bjwsafv\n" +
            "\n" +
            "rstwnlif\n" +
            "lrqsifwn\n" +
            "enflywbsuirm\n" +
            "frvilwsn\n" +
            "\n" +
            "hsxelyjfwucpmrziqtgo\n" +
            "yacmkivbfsxgonqjz\n" +
            "\n" +
            "vdpukihqgnc\n" +
            "vgprqiscnthkud\n" +
            "dvchuipenqkg\n" +
            "haivnkqpcudg\n" +
            "kuvcdipgnqh\n" +
            "\n" +
            "zcrdpbi\n" +
            "prdibzc\n" +
            "cdpqbrzi\n" +
            "rzicdpb\n" +
            "ribpczd\n" +
            "\n" +
            "yfazwxeihqvocpr\n" +
            "bjmkhuldtgsn\n" +
            "\n" +
            "p\n" +
            "xedbl\n" +
            "\n" +
            "soqby\n" +
            "sotkqm\n" +
            "pgresbm\n" +
            "vpsm\n" +
            "nzufwljs\n" +
            "\n" +
            "byakldxptwcjsiveho\n" +
            "owuizctyslab\n" +
            "\n" +
            "mhrzloeiqcs\n" +
            "hokimzsqclr\n" +
            "hiscqlmyorz\n" +
            "mloqisrhczk\n" +
            "qoimhsrlcz\n" +
            "\n" +
            "uzr\n" +
            "gwequmljtsz\n" +
            "uiafzo\n" +
            "uzfd\n" +
            "\n" +
            "sp\n" +
            "p\n" +
            "lmupfk\n" +
            "p\n" +
            "px\n" +
            "\n" +
            "cgkzn\n" +
            "aqs\n" +
            "yl\n" +
            "as\n" +
            "\n" +
            "qpujg\n" +
            "hsqpyvke\n" +
            "\n" +
            "baenkcjylfm\n" +
            "aerkcnlmqfy\n" +
            "\n" +
            "vskbapcx\n" +
            "kasvwxp\n" +
            "\n" +
            "empwustrcoxfhq\n" +
            "xetsqomhfjcpuwrn\n" +
            "wqxershpumofct\n" +
            "pqushctreomwyxf\n" +
            "qowfpcrsmxehut\n" +
            "\n" +
            "ngtuvzhswm\n" +
            "uaejfomtkdhxg\n" +
            "\n" +
            "fjyg\n" +
            "gyfj\n" +
            "gfjyl\n" +
            "ajfyg\n" +
            "gnayfj\n" +
            "\n" +
            "beunsyft\n" +
            "ngwijdahyu\n" +
            "xusltnyeb\n" +
            "nuymc\n" +
            "\n" +
            "ehjtypbnz\n" +
            "nzbpjeht\n" +
            "\n" +
            "wlvjeuonfxamtdkyh\n" +
            "zyxetvolrfumkajndh\n" +
            "yhdelsnmkvfxajquto\n" +
            "dajvxkmoulywfnteh\n" +
            "paxvofkdijcuyehnmtl\n" +
            "\n" +
            "wokleznhtfujvsyi\n" +
            "esuihwtvmolknzyfg\n" +
            "wtxounhekyflvsiz\n" +
            "\n" +
            "jmxdruoe\n" +
            "mroqxudeh\n" +
            "dumexro\n" +
            "mudorex\n" +
            "rmudoxe\n" +
            "\n" +
            "znwimsoye\n" +
            "lnm\n" +
            "\n" +
            "iduvmxqajc\n" +
            "dicaxomvuq\n" +
            "cqamxuido\n" +
            "bmuxadqci\n" +
            "qsuxlraehcdmkpi\n" +
            "\n" +
            "fsvkmx\n" +
            "yejowu\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "ce\n" +
            "cx\n" +
            "\n" +
            "rgisypzduoafqenlvbtkchx\n" +
            "ubrpaoylztchesxinvdfkqg\n" +
            "hxoeztdngyfpavrqibkulcs\n" +
            "\n" +
            "xwudgpln\n" +
            "hdvbyfergxlu\n" +
            "rdgxluy\n" +
            "\n" +
            "duzxrwnbpam\n" +
            "mnrpudasbxwz\n" +
            "pwadxrnuzmb\n" +
            "wnuxrbdpamz\n" +
            "punrmzbwaxd\n" +
            "\n" +
            "txfcywbrpqdo\n" +
            "xtdrbcfowypq\n" +
            "\n" +
            "ph\n" +
            "h\n" +
            "xcah\n" +
            "h\n" +
            "\n" +
            "dupzmylvkoexhbnqia\n" +
            "hnbxjpdylvakezqmic\n" +
            "mxvdkzpyqenhlbia\n" +
            "qlihkeuzmabxvtdnpsry\n" +
            "lndvfyxzkopbiehqamw\n" +
            "\n" +
            "pzhqidceusavftrbmj\n" +
            "mrhftapzujqdb\n" +
            "qrufxpbthajzdm\n" +
            "\n" +
            "ejzrvwf\n" +
            "rewzfjv\n" +
            "zjwfevr\n" +
            "rwejzvf\n" +
            "\n" +
            "dh\n" +
            "hd\n" +
            "dh\n" +
            "dh\n" +
            "hd\n" +
            "\n" +
            "unpxarehjdtvfcbi\n" +
            "neutmazvipjgxdh\n" +
            "ahvdnuejtixzp\n" +
            "vjmuyldapnkxhtei\n" +
            "ntvkhdxpgozqujeai\n" +
            "\n" +
            "hwxnscaozpdvmykfr\n" +
            "ymnakxuocsbwtlhfpir\n" +
            "\n" +
            "zjrxsc\n" +
            "xrcnzisubwjkv\n" +
            "\n" +
            "ambgxr\n" +
            "argxmb\n" +
            "gxbam\n" +
            "gbmxa\n" +
            "xabglmh\n" +
            "\n" +
            "hdoqbximyjpsanc\n" +
            "qjyohadpbiscx\n" +
            "\n" +
            "oaxmgcrlufztn\n" +
            "gnatcirxlmfz\n" +
            "umxarzfncgtw\n" +
            "zjgnqmtdpckfhayresx\n" +
            "\n" +
            "ivtwqcunjp\n" +
            "vqfucptljihw\n" +
            "ncuwvitjqp\n" +
            "tcjrwpvqsiyux\n" +
            "\n" +
            "fjixvbl\n" +
            "lfvbo\n" +
            "lfbv\n" +
            "\n" +
            "zojqrydtabghp\n" +
            "drgxqynj\n" +
            "\n" +
            "sk\n" +
            "jse\n" +
            "nxcsui\n" +
            "deos\n" +
            "szfk\n" +
            "\n" +
            "tmikxzohgyndcbjafuqpv\n" +
            "cvybqpfouigjkdhanxtm\n" +
            "xvckufbaqnhjdmgipoyt\n" +
            "canqkvfgmhipdjbyxtou\n" +
            "\n" +
            "bjqcdzy\n" +
            "zxjtcbyeqwv\n" +
            "\n" +
            "qcjtnyeurskdmgixbv\n" +
            "cvdmrtsjgxbyoekiqu\n" +
            "riytuqxdmevgsjkcb\n" +
            "\n" +
            "kzmfdtouep\n" +
            "omukctzdepf\n" +
            "\n" +
            "tjo\n" +
            "kfpjx\n" +
            "wjfuo\n" +
            "cijn\n" +
            "\n" +
            "bcoepgd\n" +
            "xcduofge\n" +
            "eodgtc\n" +
            "\n" +
            "ourfgclz\n" +
            "mjyvexginqkop\n" +
            "ughfadtbos\n" +
            "\n" +
            "eyrojsbd\n" +
            "jsbrdeyo\n" +
            "jydebsro\n" +
            "erbyojds\n" +
            "odjgzbrisqehy\n" +
            "\n" +
            "ejtwasqflokdivyxmgnb\n" +
            "xscwtfmyuiqrek\n" +
            "\n" +
            "mirxqkfatbysz\n" +
            "viegbdjwlpch\n" +
            "\n" +
            "egnvzfmbxduh\n" +
            "jbmvkgdneux\n" +
            "xnvumgyrebd\n" +
            "omcivlsnuwegbxad\n" +
            "tuexnmzgvdb\n" +
            "\n" +
            "kpyfabhiq\n" +
            "hpqkibya\n" +
            "\n" +
            "ryqlscavmi\n" +
            "svlo\n" +
            "twslv\n" +
            "ovsld\n" +
            "suhvkl\n" +
            "\n" +
            "d\n" +
            "xda\n" +
            "d\n" +
            "di\n" +
            "d\n" +
            "\n" +
            "gmydaz\n" +
            "pvjyrhx\n" +
            "vxrhye\n" +
            "\n" +
            "pmxn\n" +
            "pxm\n" +
            "ymxp\n" +
            "xmp\n" +
            "\n" +
            "lsktqzeodcf\n" +
            "zldkqojstfec\n" +
            "edfkqsocl\n" +
            "skdeqcfolw\n" +
            "\n" +
            "wjocuxbgyzt\n" +
            "jfkbwxutgzcyor\n" +
            "wuzjxyortibg\n" +
            "joyclzxtdigwub\n" +
            "puvgqojbztxmwsy\n" +
            "\n" +
            "bgnpflcimzu\n" +
            "emidgawlnpcf\n" +
            "\n" +
            "cpyvdfhunkqi\n" +
            "iouja\n" +
            "wiub\n" +
            "\n" +
            "gydetkof\n" +
            "dlykgethi\n" +
            "wtameurjgdbky\n" +
            "kegqyvdti\n" +
            "hnsykdget\n" +
            "\n" +
            "cf\n" +
            "cf\n" +
            "fc\n" +
            "\n" +
            "rvfjwkpmyxaunl\n" +
            "knarjfvwpmuxyl\n" +
            "vjapkmrlufynxw\n" +
            "yplafmknjvrwux\n" +
            "\n" +
            "vguhiezflwxspkbtqmoyd\n" +
            "puteyokqzbigsxwvfmdlh\n" +
            "khuwgdieqlxsfbotzvmpy\n" +
            "\n" +
            "xji\n" +
            "yjx\n" +
            "yxj\n" +
            "\n" +
            "ialzkged\n" +
            "ikldea\n" +
            "idak\n" +
            "adnik\n" +
            "keidal\n" +
            "\n" +
            "zb\n" +
            "ezbh\n" +
            "\n" +
            "shjrvnmbu\n" +
            "mvrnjhsu\n" +
            "ushnmvjr\n" +
            "vsjmrnhu\n" +
            "sjhmnurv\n" +
            "\n" +
            "z\n" +
            "w\n" +
            "w\n" +
            "w\n" +
            "\n" +
            "ngbfjzuyilokmwvspqca\n" +
            "nwqdcjigabukmsvolzyef\n" +
            "aihjuwsbkvnqgzltmxfyco\n" +
            "dfuzmajnlqgrvbwskycoi\n" +
            "\n" +
            "ialhtkpdrb\n" +
            "manyitxpv\n" +
            "\n" +
            "zroguqymhbvlc\n" +
            "eysrdiwtbzl\n" +
            "bzflyxtrd\n" +
            "\n" +
            "abtzviypku\n" +
            "abitpvyu\n" +
            "vuiaybtpr\n" +
            "rpybutiav\n" +
            "ptiuavyb\n" +
            "\n" +
            "sjuyplfgmxae\n" +
            "jyfegmxlaups\n" +
            "xguypsajemlf\n" +
            "\n" +
            "amclkusofjvxyz\n" +
            "xowfsvjkcrzma\n" +
            "msvckofzajx\n" +
            "vmcsoxhzjkbatep\n" +
            "xukoznaqvylfjswmc\n" +
            "\n" +
            "yzu\n" +
            "yuz\n" +
            "cimhkuvyfa\n" +
            "zyur\n" +
            "tyu\n" +
            "\n" +
            "lmp\n" +
            "gvxj\n" +
            "trhe\n" +
            "ozifaycsunkq\n" +
            "\n" +
            "hd\n" +
            "hd\n" +
            "shd\n" +
            "hd\n" +
            "\n" +
            "m\n" +
            "txm\n" +
            "nbm\n" +
            "\n" +
            "nqlaphdgomjebrfvc\n" +
            "amchdvgpjbonife\n" +
            "\n" +
            "zerdfgybc\n" +
            "dfcrgeyz\n" +
            "zergycdf\n" +
            "frdkzoeyagc\n" +
            "dyrezgfcl\n" +
            "\n" +
            "xabho\n" +
            "hoxab\n" +
            "\n" +
            "fovcsphual\n" +
            "fshuepymgc\n" +
            "\n" +
            "igstwqkfryhceomauxz\n" +
            "kfeutacrzgxwqolv\n" +
            "zxdwkfrqcjgutvaoel\n" +
            "\n" +
            "uorhnjfdmezspvblw\n" +
            "hbzvupelftkmarjwnc\n" +
            "jlxqerbgvwnmfyzih\n" +
            "\n" +
            "epudwyxzovrh\n" +
            "tgfmnqyeupb\n" +
            "yuintmebp\n" +
            "\n" +
            "bjv\n" +
            "bvj\n" +
            "vbj\n" +
            "jvb\n" +
            "jvb\n" +
            "\n" +
            "mnyzfq\n" +
            "mfyzq\n" +
            "fzyqm\n" +
            "zymfq\n" +
            "\n" +
            "dpiv\n" +
            "pidqv\n" +
            "dcpugiymwvlzj\n" +
            "pevid\n" +
            "idnvpe\n" +
            "\n" +
            "kxybcriamhlfv\n" +
            "mavlcyikbhwjx\n" +
            "amvicbxyklhu\n" +
            "\n" +
            "tv\n" +
            "tv\n" +
            "\n" +
            "elyvghamdrfzsbwpijqx\n" +
            "kszfhbxrmgdeyjqvnlpw\n" +
            "\n" +
            "hviyodxzabqkgljtewprms\n" +
            "dqeacvbpiglkwxmjtroyz\n" +
            "dvgajqriwekbmyoxltzph\n" +
            "ylomtzqwudgnfevprjaxkbi\n" +
            "\n" +
            "pbyfdcxwezuvkm\n" +
            "myfxeuczvbsw\n" +
            "umzxewvbyfc\n" +
            "\n" +
            "tygrhvlie\n" +
            "ymrgjistqlzv\n" +
            "lpnuybxwkr\n" +
            "\n" +
            "aj\n" +
            "a\n" +
            "ai\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "u\n" +
            "u\n" +
            "u\n" +
            "\n" +
            "juobn\n" +
            "odn\n" +
            "\n" +
            "wvacjmth\n" +
            "paghjmcwtqov\n" +
            "thvjwmcaz\n" +
            "zchajivwmtu\n" +
            "\n" +
            "cfnwp\n" +
            "pfnc\n" +
            "pgcyxfn\n" +
            "\n" +
            "ocrhstamfnjqpxkvzw\n" +
            "brsafjgtzdmviuoxhqnkylp\n" +
            "mkpeqovsjnrfhaxzt\n" +
            "\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "jsgoxre\n" +
            "yujew\n" +
            "mcaenfdlk\n" +
            "uwte\n" +
            "vqjies\n" +
            "\n" +
            "qxsabopvlgudneci\n" +
            "sngcubqeopadwlvihtx\n" +
            "\n" +
            "tidnobhwfp\n" +
            "xezavqskg\n" +
            "\n" +
            "isepzym\n" +
            "eysizmp\n" +
            "psewyciz\n" +
            "zeisyvmp\n" +
            "\n" +
            "dejxbcgqaoypsv\n" +
            "cqsexapnfybdokvtg\n" +
            "ovegbaxzqpdmscy\n" +
            "\n" +
            "jbqeftpghynaowsxvlmdrizcku\n" +
            "wrvipautmecxlkqyfnozbgdjsh\n" +
            "\n" +
            "vtlxswhrmpay\n" +
            "tvyaremlhpswx\n" +
            "vnmsalwhytxp\n" +
            "ixmtyphlsbawcv\n" +
            "lvatxswhuymqp\n" +
            "\n" +
            "ckzyfdrjgsubi\n" +
            "oagesyvdufzh\n" +
            "gyfauzsdh\n" +
            "yshuzfgdn\n" +
            "\n" +
            "khmvfunqtcyj\n" +
            "qujktfnmyohvc\n" +
            "jnktycmqufhv\n" +
            "\n" +
            "zeyfuvamg\n" +
            "lhnm\n" +
            "wxjiptqcbos\n" +
            "\n" +
            "g\n" +
            "g\n" +
            "\n" +
            "flrvoenpzjasgdi\n" +
            "bsvkecnaoqmfhxly\n" +
            "\n" +
            "lkws\n" +
            "kwixsloj\n" +
            "asy\n" +
            "\n" +
            "g\n" +
            "g\n" +
            "g\n" +
            "\n" +
            "egquipy\n" +
            "yagmqsdu\n" +
            "\n" +
            "uyxchzlpnows\n" +
            "lphyoc\n" +
            "oihpycal\n" +
            "pyjohlc\n" +
            "\n" +
            "cjh\n" +
            "jch\n" +
            "\n" +
            "k\n" +
            "k\n" +
            "s\n" +
            "\n" +
            "cisxvrpqumhzb\n" +
            "jagkxfvml\n" +
            "dkwotxnmglve\n" +
            "\n" +
            "ik\n" +
            "iks\n" +
            "ikc\n" +
            "ik\n" +
            "\n" +
            "rfoautyjcs\n" +
            "qhmebwn\n" +
            "\n" +
            "ovcetwn\n" +
            "tnkecwivg\n" +
            "wlntvec\n" +
            "\n" +
            "fyxmz\n" +
            "txiwmfy\n" +
            "\n" +
            "cwxjzeruktg\n" +
            "wrypvkdzo\n" +
            "nkmxrzjlw\n" +
            "\n" +
            "gyvm\n" +
            "lch\n" +
            "\n" +
            "vitykdw\n" +
            "dtoiwyvk\n" +
            "dwkiyrtav\n" +
            "kvdywit\n" +
            "kitwdhyv\n" +
            "\n" +
            "gljscbkptmuwdarehvfzx\n" +
            "cehwadmkxprgujfiszbltv\n" +
            "\n" +
            "tpvhwogzkn\n" +
            "hgvznstjepo\n" +
            "gptzsvnoh\n" +
            "\n" +
            "orcaxvhnjy\n" +
            "vrclbsneqzuth\n" +
            "\n" +
            "v\n" +
            "v\n" +
            "uo\n" +
            "q\n" +
            "qs\n" +
            "\n" +
            "uiqke\n" +
            "havwbnrmdyxs\n" +
            "jzo\n" +
            "\n" +
            "nwpytxsofkqc\n" +
            "mkslngctoqf\n" +
            "vmtolaxsqfczwny\n" +
            "efsdctrnujboqi\n" +
            "\n" +
            "sdphkmevgfojqw\n" +
            "edwyulfgzsanh\n" +
            "hiecwsrtvgdf\n" +
            "\n" +
            "uhf\n" +
            "fhu\n" +
            "\n" +
            "lzemtjfyhpnxk\n" +
            "txlefznkjmphy\n" +
            "zmhftleynjkxp\n" +
            "\n" +
            "pqtsgmdjhcwlvxrkfuaoz\n" +
            "rkvqpoamlxdjsfwugzthc\n" +
            "\n" +
            "pe\n" +
            "vwnm\n" +
            "\n" +
            "xlihufqvdbgsjm\n" +
            "lfjsvdqmxguib\n" +
            "\n" +
            "p\n" +
            "yoj\n" +
            "pk\n" +
            "k\n" +
            "m\n" +
            "\n" +
            "ohyktq\n" +
            "kyhoqt\n" +
            "khoytq\n" +
            "\n" +
            "xgtdc\n" +
            "m\n" +
            "u\n" +
            "j\n" +
            "u\n" +
            "\n" +
            "v\n" +
            "v\n" +
            "v\n" +
            "\n" +
            "zpxcaklowhdqyr\n" +
            "dzarhwckyoplqx\n" +
            "kzqyvalcdwxhorp\n" +
            "wpkcqyorlxdhza\n" +
            "qyjwzalcxhdrokp\n" +
            "\n" +
            "tg\n" +
            "sxoudyrhjc\n" +
            "lgpt\n" +
            "i\n" +
            "ie\n" +
            "\n" +
            "skm\n" +
            "ifgbx\n" +
            "\n" +
            "bvewndxcjsmgpquzrktl\n" +
            "dgbpmzlqnxcstrvjkuew\n" +
            "\n" +
            "t\n" +
            "q\n" +
            "\n" +
            "yglwujzrontkcbi\n" +
            "patmekqvbd\n" +
            "\n" +
            "binesf\n" +
            "spfnkb\n" +
            "ytbrdf\n" +
            "qbzflmuwh\n" +
            "\n" +
            "ezqyinodawmughprsbtl\n" +
            "fwmbavreqtpzdyugcho\n" +
            "tpgvuqmwbzexrodhya\n" +
            "augozfrhtjekyqwbdmp\n" +
            "\n" +
            "qbil\n" +
            "qsvilbd\n" +
            "dliqb\n" +
            "ueblqn\n" +
            "qbvdl\n" +
            "\n" +
            "kywszda\n" +
            "cdyajwh\n" +
            "\n" +
            "ivyxf\n" +
            "xnfv\n" +
            "cfvkx\n" +
            "\n" +
            "msbprdixz\n" +
            "vujcwqktb\n" +
            "wvnfgjlob\n" +
            "qknehauybfgt\n" +
            "\n" +
            "ijdlktyzqahucpxvmngb\n" +
            "uwstlbykiofpzejvhmqdxg\n" +
            "tkudxzvmqrlpjhyibg\n" +
            "pmuynigkxbdtlhqvjz\n" +
            "xqlizvpthjdgybkmu\n" +
            "\n" +
            "bszwt\n" +
            "sbtw\n" +
            "\n" +
            "krnxtjewz\n" +
            "xhtamyrpzwcnb\n" +
            "\n" +
            "hfpbkaxd\n" +
            "fdazxpikehb\n" +
            "xapdkhfb\n" +
            "\n" +
            "bucfkosvdwrhey\n" +
            "ljxnmiyhfaqrovpuet\n" +
            "\n" +
            "zby\n" +
            "umaeoq\n" +
            "r\n" +
            "yctf\n" +
            "\n" +
            "slzfeatm\n" +
            "ztealsufr\n" +
            "fzrselat\n" +
            "zflghsatev\n" +
            "zlfsatek\n" +
            "\n" +
            "u\n" +
            "u\n" +
            "u\n" +
            "\n" +
            "hrnpfxtaucywvijgkm\n" +
            "ckxmhsvwbyuntrpia\n" +
            "\n" +
            "hfbctj\n" +
            "cbmqehj\n" +
            "kupijcbh\n" +
            "\n" +
            "zqoakuwsilpvxcghryj\n" +
            "kwrovlhgqaixd\n" +
            "gkqlvimrawhxo\n" +
            "exkagblhqovwri\n" +
            "qarhivxkgbwlo\n" +
            "\n" +
            "zagubty\n" +
            "ajteugbyszp\n" +
            "aiqtgyzvbu\n" +
            "vbzatygu\n" +
            "gzybtua\n" +
            "\n" +
            "fuegqxobhnrj\n" +
            "ohbrgenfqxju\n" +
            "djqnwgoaxebrhu\n" +
            "bxergfujhoqn\n" +
            "\n" +
            "zhsvktuoiljaqcbfmxpdey\n" +
            "emzklbtdxjqfpgcsvyowiuha\n" +
            "\n" +
            "zyqknjwifrgbosd\n" +
            "izxynwgsfdqrjlobku\n" +
            "hnrbqdzfjkyigwso\n" +
            "\n" +
            "dqwkub\n" +
            "dwacqubkve\n" +
            "luymsfbnhdwxqk\n" +
            "\n" +
            "rksnm\n" +
            "smnk\n" +
            "snbkm\n" +
            "skmn\n" +
            "\n" +
            "vhxsaniezkdyqrbpowumcftl\n" +
            "mhkgarwctovznlfpsxbudeq\n" +
            "\n" +
            "rpmkdzohwslfxbvu\n" +
            "wpkmuxblzosdvrfh\n" +
            "orpmuvxlnkbzhfdswj\n" +
            "wmflpkorxuhsdzvb\n" +
            "dfpszxmbwhkroqvgul\n" +
            "\n" +
            "awkrmqyfugihdlc\n" +
            "rnqlfacihdykmewug\n" +
            "fdmagkltuczpbyqirhw\n" +
            "ufcyhwqrmldigaxk\n" +
            "\n" +
            "iedbftckjlxrsuwq\n" +
            "tiqwbgdrjefanulx\n" +
            "\n" +
            "qeimrg\n" +
            "tqzmeki\n" +
            "kefmqzti\n" +
            "eiqmn\n" +
            "\n" +
            "zqufkvrhcbywijaxd\n" +
            "tusldcywvofazqrbijx\n" +
            "\n" +
            "lehzwtvxfyoc\n" +
            "qsukjbgm\n" +
            "rpiunad\n" +
            "\n" +
            "kfelouicxwp\n" +
            "uplkfeio\n" +
            "ohfpkeiul\n" +
            "\n" +
            "tqsxozawihuvprngb\n" +
            "tnxghrqabuovizwsp\n" +
            "\n" +
            "tjqzdv\n" +
            "tvgr\n" +
            "vt\n" +
            "ztv\n" +
            "vt\n" +
            "\n" +
            "dblxqy\n" +
            "dqlnyxb\n" +
            "lyqdbx\n" +
            "qbxydl\n" +
            "\n" +
            "qwy\n" +
            "qjwhvnpt\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "vranojk\n" +
            "qipvkrteaw\n" +
            "basxdvulcmrgyf\n" +
            "\n" +
            "pgozlmirnsctahb\n" +
            "ivuykjmdpwe\n" +
            "\n" +
            "yaipskjmn\n" +
            "xpew\n" +
            "zqhepg\n" +
            "bltrp\n" +
            "vbput\n" +
            "\n" +
            "xetlrksbqajwnhdicypzfm\n" +
            "lqerwsjxphmkanzitfcdyb\n" +
            "zjnpcesfyhrlambwktxidq\n" +
            "dbfjlwapietrqsmkcznhyx\n" +
            "\n" +
            "zsjy\n" +
            "maxcifhlq\n" +
            "n\n" +
            "ys\n" +
            "jsn\n" +
            "\n" +
            "ugidx\n" +
            "qxdu\n" +
            "dacuxq\n" +
            "ezxwydvhslpormjkfbtn\n" +
            "\n" +
            "recfdjwyo\n" +
            "jrouehwydxp\n" +
            "\n" +
            "tiyvjfrq\n" +
            "rqdtfp\n" +
            "ckbtqhrozf\n" +
            "\n" +
            "v\n" +
            "v\n" +
            "kv\n" +
            "v\n" +
            "\n" +
            "vp\n" +
            "p\n" +
            "px\n" +
            "xp\n" +
            "\n" +
            "uynizpqwjxkhmbvtgsfoclr\n" +
            "buzwrpmectjsgloivqfkndhyx\n" +
            "hyowxkugrpitmjnfzblvsqc\n" +
            "\n" +
            "xhiycdtgepjl\n" +
            "fxphgbjktyerdq\n" +
            "pgyitehxcjd\n" +
            "\n" +
            "oxldsck\n" +
            "zywgis\n" +
            "\n" +
            "likygc\n" +
            "lcikyg\n" +
            "yilckg\n" +
            "gkyilc\n" +
            "dwkcgliya\n" +
            "\n" +
            "h\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "prgqxumtzovicelsh\n" +
            "euvhormzicstlgq\n" +
            "snihlgwfmzvuocqyre\n" +
            "\n" +
            "kitcamjohx\n" +
            "pusaltxich\n" +
            "tchmxkia\n" +
            "xchiat\n" +
            "xfchtzigaqv\n" +
            "\n" +
            "cgr\n" +
            "h\n" +
            "h\n" +
            "f\n" +
            "o\n" +
            "\n" +
            "kj\n" +
            "kj\n" +
            "koj\n" +
            "jk\n" +
            "kj\n" +
            "\n" +
            "rcjq\n" +
            "krm\n" +
            "\n" +
            "swnj\n" +
            "jwsno\n" +
            "wnjs\n" +
            "\n" +
            "vsucrmkdjnpbyt\n" +
            "ehxgoaiqwls\n" +
            "\n" +
            "ojywsnupzdbgt\n" +
            "zqoptdyujsrgnbw\n" +
            "gzpotujiydnwsb\n" +
            "\n" +
            "ozjwdi\n" +
            "tmvarxqc\n" +
            "\n" +
            "twp\n" +
            "pwt\n" +
            "wtp\n" +
            "wtp\n" +
            "wctp\n" +
            "\n" +
            "zibgtnfowlkyruxhpe\n" +
            "uwziljodbxvehysqkgp\n" +
            "bwnheixgoycutlakzp\n" +
            "\n" +
            "ehsrkiza\n" +
            "rxkzihqv\n" +
            "hmzkrcb\n" +
            "qrkhoz\n" +
            "ywjfdhpgklztru\n" +
            "\n" +
            "zndvtbpou\n" +
            "rfw\n" +
            "r\n" +
            "y\n" +
            "\n" +
            "clhiwkmxsvzoquagpytdfrje\n" +
            "zeodtrpwlfgcmaihyuqxkv\n" +
            "agmvowehlxquckirtzdpfy\n" +
            "\n" +
            "yfmcpjv\n" +
            "pmyjvcf\n" +
            "mvjocpfy\n" +
            "vjmfyacp\n" +
            "\n" +
            "zfcski\n" +
            "mbezo\n" +
            "pxhujald\n" +
            "wneyvz\n" +
            "\n" +
            "abjwrpqvityznofe\n" +
            "vcdpeznhiftkqw\n" +
            "xwutempzvn\n" +
            "qfpswevdgnztlh\n" +
            "\n" +
            "ioxharsyepdvqlw\n" +
            "msqaevlypdr\n" +
            "rplyqfbadvks\n" +
            "\n" +
            "jyz\n" +
            "bahjup\n" +
            "dsywnj\n" +
            "fozjd\n" +
            "jy\n" +
            "\n" +
            "brhwnqkdlmp\n" +
            "kribwmdnehlp\n" +
            "szxfcmbwnpgradujvy\n" +
            "btrnewmpdi\n" +
            "\n" +
            "xjecqo\n" +
            "zqjconapx\n" +
            "cijxqs\n" +
            "qxvcnoj\n" +
            "\n" +
            "eiuvwqlgcfdtmaxskzro\n" +
            "mkdzsoxftialguvwjqerc\n" +
            "fgtqrlkudwxoaceszmvi\n" +
            "vpmetxkwgbscoqdrulfaiz\n" +
            "\n" +
            "tdsifoa\n" +
            "ntoavhsi\n" +
            "tqiahcos\n" +
            "\n" +
            "cmfieopwahbv\n" +
            "iwmehavbpcof\n" +
            "\n" +
            "qkatb\n" +
            "pzixl\n" +
            "\n" +
            "gsml\n" +
            "lgms\n" +
            "\n" +
            "icvsozwrtmhkdjqbpanfey\n" +
            "zjfvoepnqricwktabmsyh\n" +
            "ajnfhsreqzivycwtmpobk\n" +
            "mwonbckpqefzithsavyrj\n" +
            "\n" +
            "zsjcxfrkhbdtnqiup\n" +
            "jutaqzfknhcsrpxbdi\n" +
            "jcndflxkirptqubzs\n" +
            "iykvqgtpcwrfujmbsnxzd\n" +
            "jztxdnseicoqfrukpb\n" +
            "\n" +
            "scenvazqugw\n" +
            "luntgxszvace\n" +
            "abunzgsecqv\n" +
            "vaszcugnefy\n" +
            "sunczwrgavde\n" +
            "\n" +
            "rju\n" +
            "r\n" +
            "qro\n" +
            "reknclbha\n" +
            "rdzw\n" +
            "\n" +
            "wih\n" +
            "hwi\n" +
            "\n" +
            "igovmnr\n" +
            "gzrnivom\n" +
            "mfgavdsryxoi\n" +
            "wglvqmjiubehork\n" +
            "mirgvpot\n" +
            "\n" +
            "mdg\n" +
            "mgd\n" +
            "\n" +
            "uyfvo\n" +
            "uyvof\n" +
            "\n" +
            "xopjzuklndgf\n" +
            "clngzxkofudjwp\n" +
            "khozlufrxgdpn\n" +
            "\n" +
            "axcigphuyorenk\n" +
            "udxlvwbhknsgfajtmrq\n" +
            "\n" +
            "mqza\n" +
            "wxfmal\n" +
            "\n" +
            "wd\n" +
            "yuw\n" +
            "\n" +
            "lpxki\n" +
            "ixlp\n" +
            "lpix\n" +
            "ilpx\n" +
            "fplxnij\n" +
            "\n" +
            "jsmthniyukolfaqec\n" +
            "jenatzwpbdryuvgx\n" +
            "\n" +
            "buwdmtjlr\n" +
            "lbmjwtd\n" +
            "\n" +
            "gqdtopfcb\n" +
            "tfbypogdcq\n" +
            "mtposqzdfcebxgk\n" +
            "ygdbqotpifc\n" +
            "lpgbdtcfoqi\n" +
            "\n" +
            "pyqdsubkejzctra\n" +
            "jiahmlpqdgyxfo\n" +
            "\n" +
            "evlxmzhq\n" +
            "eqxmvjnzchl\n" +
            "lzvhmqex\n" +
            "\n" +
            "tpzk\n" +
            "zhtkpg\n" +
            "tzkp\n" +
            "\n" +
            "kdyjimzvbagonslpxq\n" +
            "balpiexgyvjkzcornm\n" +
            "ozviykmgsbxpalnj\n" +
            "gnlxyqjbvozkmspai\n" +
            "mkvbajynlgixpoz\n" +
            "\n" +
            "hiyxwueazmcjbnrogq\n" +
            "fityqdgnrmabhvejowk\n" +
            "\n" +
            "eonwsb\n" +
            "bnsow\n" +
            "swnbo\n" +
            "obsnw\n" +
            "sownb\n" +
            "\n" +
            "fhpeiqlwkbnuavzgtjm\n" +
            "bizwosvgdxknypqmclr\n" +
            "\n" +
            "hvgyfuewsntdqx\n" +
            "pytgednxvsqjf\n" +
            "fesxdyvgtqn\n" +
            "gycjsedfxoqvntr\n" +
            "pxqesnvtgdfrcy\n" +
            "\n" +
            "x\n" +
            "x\n" +
            "x\n" +
            "xsv\n" +
            "\n" +
            "zugbqpdfrx\n" +
            "brofpxvzmgu\n" +
            "pxluwhzfbgqr\n" +
            "xypfgzbur\n" +
            "\n" +
            "jypuex\n" +
            "euyxp\n" +
            "eypxu\n" +
            "\n" +
            "ndehbumxg\n" +
            "tmewyxc\n" +
            "ulpesamxbkz\n" +
            "\n" +
            "cfxvelwdp\n" +
            "xplcdvfw\n" +
            "fwvdxlhcp\n" +
            "wslmpvdrxcaf\n" +
            "\n" +
            "wb\n" +
            "w\n" +
            "\n" +
            "xv\n" +
            "y\n" +
            "\n" +
            "rohtynmekalfvjpidgzcwu\n" +
            "uygwvdkmftczlainrhj\n" +
            "idzumayflcvgnhjrwtk\n" +
            "\n" +
            "vxdpbkqmgschyoul\n" +
            "jbhksqnumydc\n" +
            "qhbezridsuktmya\n" +
            "\n" +
            "gkld\n" +
            "dklg\n" +
            "kgdl\n" +
            "dlkg\n" +
            "kldg\n" +
            "\n" +
            "gxmnzys\n" +
            "xsgnm\n" +
            "xmsng\n" +
            "mnsxg\n" +
            "gimxns\n" +
            "\n" +
            "hwzuvsytkand\n" +
            "ytzukswvndah\n" +
            "dhsvkznwtuya\n" +
            "bukhazxwnvsytd\n" +
            "\n" +
            "dlmthcunbve\n" +
            "mntbveluihcd\n" +
            "qjcnhgtdbvzlume\n" +
            "mbvuelhdntc\n" +
            "\n" +
            "qmjoxsfduwrpyech\n" +
            "ymdophcswxreujfq\n" +
            "fhpxqrowmcjuesdy\n" +
            "yfjmewqospudxchr\n" +
            "mwdouqjfhexscpry\n" +
            "\n" +
            "okqjnaevywpfhzctgdiul\n" +
            "fqalgekohuzvdycwitjn\n" +
            "vufqibljczhaoneytkgwd\n" +
            "\n" +
            "zpdbawuoqcvex\n" +
            "vqadwoubepxzc\n" +
            "cvoaueqwzbdpx\n" +
            "azecbxdvmuqpwoy\n" +
            "\n" +
            "dwq\n" +
            "dwq\n" +
            "dwq\n" +
            "wqd\n" +
            "\n" +
            "pyjxqscdimuegblk\n" +
            "mdwkbigejpysquzcl\n" +
            "oiqlyhkcmfgubdvpjes\n" +
            "spmgiejkbtdacquly\n" +
            "beugjmpqnrylksdci\n" +
            "\n" +
            "kurjsczqilp\n" +
            "ecjvrmhqyskl\n" +
            "uqarljkpcs\n" +
            "crjksql\n" +
            "\n" +
            "fvlw\n" +
            "wvcfl\n" +
            "lfvw\n" +
            "\n" +
            "b\n" +
            "e\n" +
            "r\n" +
            "n\n" +
            "n\n" +
            "\n" +
            "uxjoeqbvchklt\n" +
            "lqwbkjxuoch\n" +
            "\n" +
            "zdmbgjest\n" +
            "zqicmvrnsdg\n" +
            "dawukpsfhoy\n" +
            "\n" +
            "bcgmjye\n" +
            "ztcg\n" +
            "wrxlvk\n" +
            "\n" +
            "vjxmoqcgslufnk\n" +
            "ogukcnlxsqf\n" +
            "qpylucnogskfex\n" +
            "\n" +
            "d\n" +
            "sx\n" +
            "im\n" +
            "py\n" +
            "d\n" +
            "\n" +
            "gjwfdasitcrzvhl\n" +
            "awngjxbveizuh\n" +
            "zxokgwinjvayh\n" +
            "\n" +
            "dsitcgaj\n" +
            "txcsrdigju\n" +
            "dgctsynrbj\n" +
            "ktzmdsjlpqcg\n" +
            "dtjsbvcgf\n" +
            "\n" +
            "globmq\n" +
            "mlobgq\n" +
            "bohmaqgl\n" +
            "\n" +
            "yzxkbjdrmpgevsuc\n" +
            "jkcugybvpsmrzxe\n" +
            "\n" +
            "cxjnq\n" +
            "jcrq\n" +
            "bkicqdfzujl\n" +
            "jceqa\n" +
            "\n" +
            "ystmjzl\n" +
            "lsgmb\n" +
            "\n" +
            "ftrmwn\n" +
            "trwmn\n" +
            "\n" +
            "pwcevirqxhlnaygbzdmsj\n" +
            "swhngauqyedlxpjmfbkirvz\n" +
            "rvdkxnpifmyhjqeslzwbga\n" +
            "nsplidxzmqbhveywjragfk\n" +
            "axpznqvhyrjlbifdegwms\n" +
            "\n" +
            "eiuojl\n" +
            "iujlo\n" +
            "\n" +
            "hsokycxlg\n" +
            "woqkzuscxeyjgl\n" +
            "ykoxigschl\n" +
            "\n" +
            "kuhvdtfqsrjmlzbnegi\n" +
            "lmqduebktgsrnivzjfh\n" +
            "qzlsfmwntjkedcgvixuhrb\n" +
            "kndehrmusglftzbviqj\n" +
            "\n" +
            "phn\n" +
            "nhp\n" +
            "phn\n" +
            "pnh\n" +
            "htnpd\n" +
            "\n" +
            "jimkxgocwdsyn\n" +
            "jgocmsxiykdnw\n" +
            "mocxkjysnwgid\n" +
            "myckxndiojsgw\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "qc\n" +
            "c\n" +
            "\n" +
            "mbzsdx\n" +
            "ckvgf\n" +
            "pjq\n" +
            "\n" +
            "jhypbcxluavqsfzk\n" +
            "uxbqvchpykszalj\n" +
            "bkyvohczwdapuqlxjst\n" +
            "\n" +
            "qnhmysckzgxiflu\n" +
            "hzqcmigklvun\n" +
            "nkidmthgclquz\n" +
            "dlniughqkcmz\n" +
            "\n" +
            "xyzjqsu\n" +
            "uqxjszy\n" +
            "sujypxzqb\n" +
            "ysujqzx\n" +
            "yuqzxjs\n" +
            "\n" +
            "nxygalsc\n" +
            "gunlscax\n" +
            "\n" +
            "uzjkfcabnmpxtw\n" +
            "lghfcxyqv\n" +
            "elfcoxi\n" +
            "sirhdfxc\n" +
            "\n" +
            "dmgkarlfz\n" +
            "bfgldrzm\n" +
            "sdmghuezclf\n" +
            "lrzfdmg\n" +
            "\n" +
            "astekwuyridcbogvzjq\n" +
            "tyozvascdkiqugrefj\n" +
            "rjseqkvpdhnoytluigcaz\n" +
            "\n" +
            "s\n" +
            "ws\n" +
            "sr\n" +
            "glevtxcis\n" +
            "\n" +
            "vk\n" +
            "vk\n" +
            "kv\n" +
            "\n" +
            "gaj\n" +
            "i\n" +
            "\n" +
            "zgurncxevkbths\n" +
            "aulthgxrzbisj\n" +
            "\n" +
            "uvsrmwbpxitcelq\n" +
            "eirqtxawpd\n" +
            "pirexwdqt\n" +
            "\n" +
            "qarbgx\n" +
            "xzwag\n" +
            "ntsdj\n" +
            "\n" +
            "ahjnzxtgmqibkeuv\n" +
            "kjiegzqmhvbxnwsual\n" +
            "vyanfjemrigqhzxkpub\n" +
            "\n" +
            "veu\n" +
            "yve\n" +
            "vy\n" +
            "cv\n" +
            "garnvts\n" +
            "\n" +
            "whgjdb\n" +
            "drh\n" +
            "nkqilevxm\n" +
            "\n" +
            "xowc\n" +
            "ocx\n" +
            "svocx\n" +
            "owcx\n" +
            "\n" +
            "lb\n" +
            "bc\n" +
            "lob\n" +
            "\n" +
            "egpsqzx\n" +
            "gxqewzspj\n" +
            "gxvsceqpz\n" +
            "sexzgvqpd\n" +
            "\n" +
            "cwrm\n" +
            "mbwu\n" +
            "kmw\n" +
            "wqmkv\n" +
            "\n" +
            "wn\n" +
            "n\n" +
            "khntv\n" +
            "nd\n" +
            "\n" +
            "not\n" +
            "one\n" +
            "ont\n" +
            "onl\n" +
            "\n" +
            "rckimhotdxjl\n" +
            "nfgtbwqcp\n" +
            "\n" +
            "jpgkrltvya\n" +
            "lftsbjuerkdpv\n" +
            "jvlprktz\n" +
            "lyrjtvgoxpk\n" +
            "tjgkvplwrzm\n" +
            "\n" +
            "qzckhypdlwftb\n" +
            "edcwysumk\n" +
            "\n" +
            "jsdzexo\n" +
            "jzoqesxnd\n" +
            "zoesjxwd\n" +
            "oxsjdbez\n" +
            "dzesxoj\n" +
            "\n" +
            "dg\n" +
            "magd\n" +
            "gd\n" +
            "gd\n" +
            "\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "\n" +
            "omvejgrputf\n" +
            "murvfoptejg\n" +
            "tgumopvrjfe\n" +
            "vpumfrjoget\n" +
            "\n" +
            "xacbqjsyvk\n" +
            "bvcjkyaqsx\n" +
            "qakcybxvjs\n" +
            "vasqjxkcyb\n" +
            "jkyvcaqxsb\n" +
            "\n" +
            "bofqhzyv\n" +
            "\n" +
            "nvhjwdom\n" +
            "jmvdnwhol\n" +
            "mdwvjhon\n" +
            "hjnmdwov\n" +
            "\n" +
            "nfpaoeitbdyvuhrs\n" +
            "nigbzpwrvkoay\n" +
            "mvjlgrixbyoanp\n" +
            "\n" +
            "gdkr\n" +
            "kdgr\n" +
            "redkg\n" +
            "drgk\n" +
            "\n" +
            "tcfnehwvj\n" +
            "jtwdcvfnhlo\n" +
            "juwhecvntf\n" +
            "\n" +
            "erohnpau\n" +
            "preahoun\n" +
            "npuheraob\n" +
            "\n" +
            "eskvwzxp\n" +
            "azxlmskpe\n" +
            "ksperizxw\n" +
            "xespkmz\n" +
            "pxzsenkcfo\n" +
            "\n" +
            "d\n" +
            "d\n" +
            "k\n" +
            "\n" +
            "eistjpgmnfhrb\n" +
            "bjkylvwac\n" +
            "\n" +
            "vbe\n" +
            "gpives\n" +
            "ve\n" +
            "ve\n" +
            "\n" +
            "mbagdqsox\n" +
            "asolmgdqtixub\n" +
            "bsdaxorgnmq\n" +
            "sbaogqdmx\n" +
            "paodsxbqgm\n" +
            "\n" +
            "crodfihjzb\n" +
            "pdoihfzrba\n" +
            "bhfzrpdowmi\n" +
            "ldfturkbozhi\n" +
            "\n" +
            "ydz\n" +
            "yd\n" +
            "yusdhj\n" +
            "dalcyz\n" +
            "\n" +
            "dqlypnmf\n" +
            "dnmpqfly\n" +
            "pynldmqf\n" +
            "rmpyqlfuwdnta\n" +
            "qmnyplfdx\n" +
            "\n" +
            "tzdbgiq\n" +
            "mbtdqzgi\n" +
            "bzdgiqt\n" +
            "ztdiqgb\n" +
            "\n" +
            "p\n" +
            "yfubzpvam\n" +
            "ip\n" +
            "\n" +
            "cnbkuvahfolsgtqr\n" +
            "ngtblsuqickhav\n" +
            "\n" +
            "qitflvsmp\n" +
            "tpfvlmsgikywq\n" +
            "mtspvqlfi\n" +
            "psqvifmtl\n" +
            "miflqpstv\n" +
            "\n" +
            "bljaqdnkosxhy\n" +
            "kdoynebqhlxs\n" +
            "\n" +
            "yvjluq\n" +
            "pcj\n" +
            "mrjsdzne\n" +
            "qj\n" +
            "\n" +
            "crqjmo\n" +
            "mqvzxrj\n" +
            "\n" +
            "czdipgjlk\n" +
            "pnkxdjcolv\n" +
            "\n" +
            "rm\n" +
            "mr\n" +
            "mr\n" +
            "\n" +
            "uegltzby\n" +
            "yltgzeb\n" +
            "goztypleb\n" +
            "lyegdztb\n" +
            "etsgzybl\n" +
            "\n" +
            "hxmqrgkpntzyldjbs\n" +
            "djigzcbnexhfomvp\n" +
            "\n" +
            "voameyfg\n" +
            "kaeofvmjl\n" +
            "xrovmkaef\n" +
            "ovmfe\n" +
            "pvneomwsctizfbq\n" +
            "\n" +
            "hxjuetbri\n" +
            "garbhldyxket\n" +
            "\n" +
            "gxnsf\n" +
            "gfsx\n" +
            "xslgf\n" +
            "mxgfs\n" +
            "sfgx\n" +
            "\n" +
            "bmuhtleiv\n" +
            "vyc\n" +
            "\n" +
            "bgch\n" +
            "hcgab\n" +
            "gbch\n" +
            "hbgc\n" +
            "\n" +
            "pk\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "tp\n" +
            "\n" +
            "fn\n" +
            "fn\n" +
            "\n" +
            "durnkjygtxqwihsbalz\n" +
            "gsntxizrdlvq\n" +
            "ilfgmoqcstrexdzn\n" +
            "\n" +
            "tqsglayz\n" +
            "lysqzgta\n" +
            "\n" +
            "r\n" +
            "r\n" +
            "r\n" +
            "r\n" +
            "\n" +
            "puizdkoaylhswb\n" +
            "gmxenctdfrjqv\n" +
            "\n" +
            "tcihvpqdb\n" +
            "ewpvicbrzthk\n" +
            "fobglycsvhiam\n" +
            "\n" +
            "ntvxahycozrewpi\n" +
            "sziaefmyxjlhnogtv\n" +
            "vwhizyutacnxeo\n" +
            "bvuonakytcexhzi\n" +
            "oinypavhtzxeb\n" +
            "\n" +
            "vuzysfaoxdihgjqnkbl\n" +
            "kdfgsivzxanyobjqhl\n" +
            "ixnsbgaydvhflqjkzo\n" +
            "\n" +
            "uwfajgzpdrhsbitkmclqvno\n" +
            "pgsnjvrwatkbzfhoqldmciu\n" +
            "ckzrswqjolgbupmvnfidhta\n" +
            "\n" +
            "squmrdowjy\n" +
            "iusrcmzyodh\n" +
            "rnlsdmxuyefoz\n";

    public int sumOfYesAnswers() {
       return sumOfYesAnswers(inputData);
    }

    public int sumOfGroupYesAnwers() {
        return sumOfGroupYesAnwers(inputData);
    }

    private int sumOfGroupYesAnwers(String data) {
        String[] groups = inputData.split("\n\n");
        int yesAnswers = 0;
        for(String group : groups) {
            yesAnswers += getNumberOfCommonYesFromGroup(group.split("\n"));
        }
        return yesAnswers;
    }

    private int sumOfYesAnswers(String inputData) {
        String[] groups = inputData.split("\n\n");
        int yesAnswers = 0;
        for(String group : groups) {
            yesAnswers += getNumberOfYesFromGroup(group.split("\n"));
        }
        return yesAnswers;
    }


    private int getNumberOfYesFromGroup(String[] group) {
        Set<Character> answers = new HashSet<>();
        for(String answer : group) {
            for(int i = 0; i< answer.length(); i++) {
                answers.add(answer.charAt(i));
            }
        }
        return answers.size();
    }

    private int getNumberOfCommonYesFromGroup(String[] group) {
        Map<Character, Integer> yesOccurances = new HashMap<>();
        for(String answer : group) {
            for(int i = 0;  i< answer.length(); i++) {
                yesOccurances.merge(answer.charAt(i), 1, Integer::sum);
            }
        }
        return (int)yesOccurances.values().stream().filter(value -> value >= group.length).count();
    }

}
